// src/UI/Components/Encounter/Encounter.vue
<template>
  <div v-if="activePersons.length > 0 && !enemiesPresent" id="encounters" class="box-container">
    <div class="box-title">{{ texts.encounters }}</div>
    <ul class="list-unstyled">
      <li v-for="person of activePersons" :class="game.combinations.getCombineClass(person)"
          @click="store.tryCombine(person)">
        <span class="person-name">{{ person.name }}</span>
        <div class="inline">
          <button v-if="person.conversation" class="btn btn-info talk" type="button" @click="talk(person)">
            {{ texts.format(texts.talk, [person.name]) }}
          </button>
          <button v-if="person.trade" class="btn btn-info trade" type="button" @click="trade(person)">
            {{ texts.format(texts.trade, [person.name]) }}
          </button>
          <button v-if="hasDescription(person)" class="btn btn-info examine" type="button"
                  @click="store.showDescription('person', person, person.name)">
            {{ texts.format(texts.examine, [person.name]) }}
          </button>
          <button v-if="person.canAttack === undefined || person.canAttack === true" class="btn btn-danger"
                  type="button" @click="startCombat(person)">{{ texts.format(texts.attack, [person.name]) }}
          </button>
        </div>
        <img v-if="person.picture" :alt="person.name" :src="person.picture" class="person-picture"/>
      </li>
    </ul>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {IPerson} from "storyScript/Interfaces/person.ts";
import {ITrade} from "storyScript/Interfaces/trade.ts";
import {hasDescription} from "storyScript/Services/sharedFunctions.ts";

const store = useStateStore();
const {game, enemiesPresent, activePersons} = storeToRefs(store);
const {texts, conversationService} = store.services;

const talk = (person: IPerson): void => conversationService.talk(person);

const trade = (trade: IPerson | ITrade): boolean => store.trade(game.value.currentLocation, trade);

const startCombat = (person: IPerson): void => store.startCombat(game.value.currentLocation, person);
</script>

// src/UI/Angular/src/Components/Encounter/encounter.component.ts
import { IGame, IInterfaceTexts, IItem, ITrade, IPerson } from '../../../../../Engine/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core'
import template from './encounter.component.html';

@Component({
    selector: 'encounter',
    template: template,
})
export class EncounterComponent {
    constructor(private _sharedMethodService: SharedMethodService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent(this.game);

    personsPresent = (): boolean => this.game.currentLocation && this.game.currentLocation.activePersons && this.game.currentLocation.activePersons.length > 0;

    getCombineClass = (item: IItem): string => this.game.combinations.getCombineClass(item);

    tryCombine = (person: IPerson): boolean => this._sharedMethodService.tryCombine(this.game, person);

    talk = (person: IPerson): void => this._sharedMethodService.talk(person);

    trade = (trade: IPerson | ITrade): boolean => this._sharedMethodService.trade(trade);
    
    startCombat = (person: IPerson): void => this._sharedMethodService.startCombat(this.game, this.texts, person);
}
<div class="box-container" id="encounters" ng-if="personsPresent() && !enemiesPresent()">
    <div class="box-title">{{ texts.encounters }}</div>
    <ul class="list-unstyled">
        <li ng-repeat="person in game.currentLocation.activePersons" ng-click="tryCombine(person)" ng-class="getCombineClass(person)">
            <span>{{ person.name }}</span>
            <div class="inline" ng-class="getCombineClass()">
                <button type="button" class="btn btn-info talk" ng-if="person.conversation" ng-click="talk(person)">{{ texts.format(texts.talk, [person.name]) }}</button>
                <button type="button" class="btn btn-info trade" ng-if="person.trade" ng-click="trade(person)">{{ texts.format(texts.trade, [person.name]) }}</button>
                <button type="button" class="btn btn-danger" ng-if="person.canAttack === undefined || person.canAttack === true" ng-click="startCombat(person)">{{ texts.format(texts.attack, [person.name]) }}</button>
            </div>
            <img src="{{ person.picture }}" ng-if="person.picture" />
        </li>
    </ul>
</div>
