// src/UI/Components/Exploration/ActionLog.vue
<template>
  <div id="action-log" class="box-container">
    <div class="box-title">{{ texts.messages }}</div>
    <ul class="action-log list-unstyled">
      <li v-for="message of game.actionLog" v-html="message"></li>
    </ul>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts} = store.services;

</script>

// src/UI/Components/ActionLog/actionlog.component.ts
import { IGame, IInterfaceTexts } from 'storyScript/Interfaces/storyScript';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component } from '@angular/core';
import template from './actionlog.component.html';

@Component({
    selector: 'action-log',
    template: template,
})
export class ActionLogComponent {
    constructor(objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;
}
<div class="box-container" id="action-log">
    <div class="box-title">{{ texts.messages }}</div>
    <ul class="action-log list-unstyled">
        @for (message of  game.actionLog; track message)
        {
            <li>{{ message }}</li>
        }
    </ul>
</div>
