// src/UI/Components/Equipment/equipment.component.ts
import {DefaultEquipment, ICharacter, IGame, IInterfaceTexts, IItem} from 'storyScript/Interfaces/storyScript';
import {SharedMethodService} from '../../Services/SharedMethodService';
import {CharacterService} from 'storyScript/Services/CharacterService';
import {ServiceFactory} from 'storyScript/ServiceFactory.ts';
import {Component, inject, Input} from '@angular/core';
import {getTemplate} from '../../helpers';
import {ItemService} from "storyScript/Services/ItemService.ts";
import {NgbCollapse} from "@ng-bootstrap/ng-bootstrap";
import {SharedModule} from "ui/Modules/sharedModule.ts";

@Component({
    standalone: true,
    selector: 'equipment',
    imports: [SharedModule, NgbCollapse],
    template: getTemplate('equipment', await import('./equipment.component.html?raw'))
})
export class EquipmentComponent {
    @Input() character!: ICharacter;
    private readonly _characterService: CharacterService;
    private readonly _itemService: ItemService;
    private readonly _sharedMethodService: SharedMethodService;

    constructor() {
        this._characterService = inject(CharacterService);
        this._itemService = inject(ItemService);
        this._sharedMethodService = inject(SharedMethodService);
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this._sharedMethodService.useEquipment = true;
    }

    game: IGame;
    texts: IInterfaceTexts;

    showEquipment = (): boolean => this._sharedMethodService.showEquipment(this.character);

    customSlots = (): string[] => {
        const defaultSlots = Object.keys(new DefaultEquipment());
        return Object.keys(this.character.equipment).filter(e => defaultSlots.indexOf(e) === -1)
    };

    getItemName = (item: IItem): string => this._itemService.getItemName(item);

    unequipItem = (item: IItem): boolean => this._itemService.unequipItem(this.character, item);

    isSlotUsed = (slot: string | string[]): boolean => {
        const slots = Array.isArray(slot) ? slot : [slot];
        return slots.find(s => this._characterService.isSlotUsed(this.character, s)) !== undefined;
    }
}
@let equipment = character.equipment;
@if (showEquipment())
{
    <div class="character-equipment box-container">
        <div class="box-title" (click)="isCollapsed = !isCollapsed">{{ texts.equipmentHeader }}</div>
        <div class="equipment-panel collapse navbar-collapse" [ngbCollapse]="isCollapsed">
            @if (isSlotUsed('head'))
            {
                <div class="row">
                    <div class="col-12">
                        <div>
                            {{ texts.head }}
                        </div>
                        <div class="item-box" (click)="unequipItem(equipment.head)">
                            {{ getItemName(equipment.head) }}
                        </div>
                    </div>
                </div>
            }
            @if (isSlotUsed('amulet'))
            {
                <div class="row">
                    <div class="col-12">
                        <div>
                            {{ texts.amulet }}
                        </div>
                        <div class="item-box" (click)="unequipItem(equipment.amulet)">
                            {{ getItemName(equipment.amulet) }}
                        </div>
                    </div>
                </div>
            }
            <div class="row">
                <div class="col-3">
                    @if (isSlotUsed(['hands', 'rightHand', 'rightRing']))
                    {
                        <span>{{ texts.rightHand }}</span>
                    }
                </div>
                <div class="col-6">
                    @if (isSlotUsed('body'))
                    {
                        <span>{{ texts.body }}</span>
                    }
                </div>
                <div class="col-3">
                    @if (isSlotUsed(['hands', 'leftHand', 'leftRing']))
                    {
                        <span>{{ texts.leftHand }}</span>
                    }
                </div>
                <div class="col-3">
                    @if (isSlotUsed('hands'))
                    {
                        <div class="item-box" (click)="unequipItem(equipment.hands)">{{ getItemName(equipment.hands) }}</div>
                    }
                    @if (isSlotUsed('rightHand'))
                    {
                        <div class="item-box" [ngClass]="{ 'side-borders' : isSlotUsed(['hands', 'rightRing']) }" (click)="unequipItem(equipment.rightHand)">{{ getItemName(equipment.rightHand) }}</div>
                    }
                    @if (isSlotUsed('rightRing'))
                    {
                        <div class="item-box" (click)="unequipItem(equipment.rightRing)">{{ getItemName(equipment.rightRing) }}</div>
                    }
                </div>
                <div class="col-6">
                    @if ((isSlotUsed(['rightHand', 'leftHand'])) && isSlotUsed('hands'))
                    {
                        <div class="item-box no-border"></div>
                    }
                    @if (isSlotUsed('body'))
                    {
                        <div class="item-box" (click)="unequipItem(equipment.body)">{{ getItemName(equipment.body) }}</div>
                    }
                </div>
                <div class="col-3">
                    @if (isSlotUsed('hands'))
                    {
                        <div class="item-box" (click)="unequipItem(equipment.hands)">{{ getItemName(equipment.hands) }}</div>
                    }
                    @if (isSlotUsed('leftHand'))
                    {
                        <div class="item-box" [ngClass]="{ 'side-borders' : isSlotUsed(['hands', 'leftRing']) }" (click)="unequipItem(equipment.leftHand)">{{getItemName(equipment.leftHand) }}</div>
                    }
                    @if (isSlotUsed('leftRing'))
                    {
                        <div class="item-box" (click)="unequipItem(equipment.leftRing)">{{ getItemName(equipment.leftRing) }}</div>
                    }
                </div>
            </div>
            @if (isSlotUsed('legs'))
            {
                <div class="row">
                    <div class="col-12">
                        <div>
                            {{ texts.legs }}
                        </div>
                        <div class="item-box" (click)="unequipItem(equipment.legs)">
                            {{ getItemName(equipment.legs) }}
                        </div>
                    </div>
                </div>
            }
            @if (isSlotUsed('feet'))
            {
                <div class="row">
                    <div class="col-12">
                        <div>
                            {{ texts.feet }}
                        </div>
                        <div class="item-box" (click)="unequipItem(equipment.feet)">
                            {{ getItemName(equipment.feet) }}
                        </div>
                    </div>
                </div>
            }
            @for (slot of customSlots(); track slot)
            {
                @if (isSlotUsed(slot))
                {
                    <div class="row">
                        <div class="col-12">
                            <div>
                                {{ texts[slot] }}
                            </div>
                            <div class="item-box" (click)="unequipItem(equipment[slot])">
                                {{ getItemName(equipment[slot]) }}
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
}

// src/UserInterface/Components/Party/Equipment.vue
<template>
  <div v-if="showEquipment(useEquipment, character)" class="character-equipment box-container">
    <collapsible :text="texts.equipmentHeader" :headerClass="'box-title'">
      <div class="equipment-panel">
        <div v-if="isSlotUsed('head')" class="row">
          <div class="col-12">
            <div>
              {{ texts.head }}
            </div>
            <div class="item-box" @click="unequipItem(character.equipment.head)">
              {{ getItemName(character.equipment.head) }}
            </div>
          </div>
        </div>
        <div v-if="isSlotUsed('amulet')" class="row">
          <div class="col-12">
            <div>
              {{ texts.amulet }}
            </div>
            <div class="item-box" @click="unequipItem(character.equipment.amulet)">
              {{ getItemName(character.equipment.amulet) }}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-3">
            <span v-if="isSlotUsed(['hands', 'rightHand', 'rightRing'])">{{ texts.rightHand }}</span>
          </div>
          <div class="col-6">
            <span v-if="isSlotUsed('body')">{{ texts.body }}</span>
          </div>
          <div class="col-3">
            <span v-if="isSlotUsed(['hands', 'leftHand', 'leftRing'])">{{ texts.leftHand }}</span>
          </div>
          <div class="col-3">
            <div v-if="isSlotUsed('hands')" class="item-box" @click="unequipItem(character.equipment.hands)">
              {{ getItemName(character.equipment.hands) }}
            </div>
            <div v-if="isSlotUsed('rightHand')" :class="{ 'side-borders' : isSlotUsed(['hands', 'rightRing']) }"
                 class="item-box"
                 @click="unequipItem(character.equipment.rightHand)">{{ getItemName(character.equipment.rightHand) }}
            </div>
            <div v-if="isSlotUsed('rightRing')" class="item-box" @click="unequipItem(character.equipment.rightRing)">
              {{ getItemName(character.equipment.rightRing) }}
            </div>
          </div>
          <div class="col-6">
            <div v-if="isSlotUsed(['rightHand', 'leftHand']) && isSlotUsed('hands')" class="item-box no-border"></div>
            <div v-if="isSlotUsed('body')" class="item-box" @click="unequipItem(character.equipment.body)">
              {{ getItemName(character.equipment.body) }}
            </div>
          </div>
          <div class="col-3">
            <div v-if="isSlotUsed('hands')" class="item-box" @click="unequipItem(character.equipment.hands)">
              {{ getItemName(character.equipment.hands) }}
            </div>
            <div v-if="isSlotUsed('leftHand')" :class="{ 'side-borders' : isSlotUsed(['hands', 'leftRing']) }"
                 class="item-box"
                 @click="unequipItem(character.equipment.leftHand)">{{ getItemName(character.equipment.leftHand) }}
            </div>
            <div v-if="isSlotUsed('leftRing')" class="item-box" @click="unequipItem(character.equipment.leftRing)">
              {{ getItemName(character.equipment.leftRing) }}
            </div>
          </div>
        </div>
        <div v-if="isSlotUsed('legs')" class="row">
          <div class="col-12">
            <div>
              {{ texts.legs }}
            </div>
            <div class="item-box" @click="unequipItem(character.equipment.legs)">
              {{ getItemName(character.equipment.legs) }}
            </div>
          </div>
        </div>
        <div v-if="isSlotUsed('feet')" class="row">
          <div class="col-12">
            <div>
              {{ texts.feet }}
            </div>
            <div class="item-box" @click="unequipItem(character.equipment.feet)">
              {{ getItemName(character.equipment.feet) }}
            </div>
          </div>
        </div>
        <div v-for="slot of customSlots()" class="row">
          <div v-if="isSlotUsed(slot)" class="col-12">
            <div>
              {{ texts[slot] }}
            </div>
            <div class="item-box" @click="unequipItem(character.equipment[slot])">
              {{ getItemName(character.equipment[slot]) }}
            </div>
          </div>
        </div>
      </div>
    </collapsible>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {DefaultEquipment} from "storyScript/Interfaces/defaultEquipment.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {showEquipment} from "vue/Helpers.ts";

const store = useStateStore();
const {useEquipment} = storeToRefs(store);
const {texts, itemService, characterService} = store.services;

const {character} = defineProps<{
  character?: ICharacter
}>();

useEquipment.value = true;

const customSlots = (): string[] => {
  const defaultSlots = Object.keys(new DefaultEquipment());
  return Object.keys(character.equipment).filter(e => defaultSlots.indexOf(e) === -1)
};

const getItemName = (item: IItem): string => itemService.getItemName(item);

const unequipItem = (item: IItem): boolean => itemService.unequipItem(character, item);

const isSlotUsed = (slot: string | string[]): boolean => {
  const slots = Array.isArray(slot) ? slot : [slot];
  return slots.find(s => characterService.isSlotUsed(character, s)) !== undefined;
}

</script>
