// src/UI/Components/Party/CharacterSheet.vue
<template>
  <div id="character-attributes" class="box-container">
    <collapsible :text="character.name || texts.characterSheet" :headerClass="'box-title'">
      <div class="character-info">
        <div v-if="character.portraitFileName" class="portraitFrame">
          <img :alt="character.name" class="portrait" :src="character.portraitFileName"/>
        </div>
        <ul id="attributes-panel" class="list-unstyled">
          <li v-for="attribute of displayCharacterAttributes">
            {{ texts.titleCase(attribute) }} {{ character[attribute] }}
          </li>
          <li>{{ texts.hitpoints }}
            <div class="hitpoint-editor">
              <span v-if="!isDevelopment">{{ character.currentHitpoints }}</span>
              <input v-else v-model="character.currentHitpoints" :max="character.hitpoints" :min="1" type="number"
                     @blur="limitInput($event, character)">
            </div>
            &nbsp;/ {{ character.hitpoints }}
          </li>
          <li v-if="party.characters.length === 1 && party.currency !== undefined">{{ texts.currency }}
            {{ party.currency }}
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
    </collapsible>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {ref} from "vue";
import {IParty} from "storyScript/Interfaces/party.ts";
import {isDevelopment} from "../../../../constants.ts";

const store = useStateStore();
const {useCharacterSheet} = storeToRefs(store);
const {texts, characterService} = store.services;

const {character} = defineProps<{
  party: IParty,
  character?: ICharacter
}>();

useCharacterSheet.value = true;

const displayCharacterAttributes = ref<string[]>(characterService.getSheetAttributes());

const limitInput = (event: any, character: ICharacter): void => {
  if (character.currentHitpoints > character.hitpoints) {
    character.currentHitpoints = character.hitpoints;
  } else if (character.currentHitpoints <= 0) {
    character.currentHitpoints = 1;
  }
}

</script>

// src/UI/Angular/src/Components/CharacterSheet/charactersheet.component.ts
import { IInterfaceTexts, IGame } from '../../../../../Engine/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { CharacterService } from '../../../../../Engine/Services/characterService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './charactersheet.component.html';

@Component({
    selector: 'character-sheet',
    template: template,
})
export class CharacterSheetComponent {
    constructor(sharedMethodService: SharedMethodService, characterService: CharacterService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this.displayCharacterAttributes = characterService.getSheetAttributes();
        sharedMethodService.useCharacterSheet = true;
    }

    game: IGame;
    texts: IInterfaceTexts;
    displayCharacterAttributes: string[];
}
<div class="box-container" id="character-attributes">
    <div class="box-title" data-toggle="collapse" data-target="#character-info">{{ game.character.name || texts.characterSheet }}</div>
    <div id="character-info" class="collapse show">
        <div id="portraitFrame">
            <img class="portrait" src="{{game.character.portraitFileName}}" />
        </div>
        <ul id="attributes-panel" class="list-unstyled">
            <li *ngFor="let attribute of displayCharacterAttributes">
                {{ texts.titleCase(texts.format(attribute)) }} {{ game.character[attribute] }}
            </li>
            <li>{{ texts.hitpoints }} {{ game.character.currentHitpoints }} / {{ game.character.hitpoints }}</li>
            <li>{{ texts.currency }} {{ game.character.currency }}</li>
        </ul>
        <div class="clearfix"></div>
    </div>
</div>
