// src/UserInterface/Components/Encounter/CombatParticipant.vue
<template>
  <h4>{{ participant.name }}</h4>
  <p :class="{ 'enemy-health': participantType === 'enemy', 'character-health': participantType === 'character' }">
    {{ texts.format(hitPointText, [participant.currentHitpoints, participant.hitpoints]) }}
  </p>
  <img v-if="participant.picture" :src="participant.picture" :alt="participant.name" />
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {computed} from "vue";

const store = useStateStore();
const {texts} = store.services;

const participantType = computed(() => participant.type ?? 'character');

const hitPointText = computed(() => participant.type ? texts.enemyHitpoints : texts.characterHitpoints);

const {participant} = defineProps<{
  participant: any
}>();

</script>

// src/UI/Components/CombatParticipant/combatparticipant.component.ts
import {Component, inject, Input} from "@angular/core";
import {getTemplate} from "../../helpers.ts";
import {ServiceFactory} from "storyScript/ServiceFactory.ts";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {IEnemy} from "storyScript/Interfaces/enemy.ts";
import {IInterfaceTexts} from "storyScript/Interfaces/interfaceTexts.ts";
import {IGame} from "storyScript/Interfaces/game.ts";
import {CommonModule} from "@angular/common";

@Component({
    standalone: true,
    selector: 'combat-participant',
    imports: [CommonModule],
    template: getTemplate('combatparticipant', await import('./combatparticipant.component.html?raw'))
})
export class CombatParticipantComponent {
    @Input() participant!: IEnemy | ICharacter;

    constructor() {
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;
}
@let participantType = participant.type ?? 'character';
@let hitpointText = participant.type ? texts.enemyHitpoints : texts.characterHitpoints;
<h4>{{ participant.name }}</h4>
<p [ngClass]="{ 'enemy-health': participantType === 'enemy', 'character-health': participantType === 'character' }" class="">
    {{ texts.format(hitpointText, [participant.currentHitpoints, participant.hitpoints]) }}
</p>
@if (participant.picture)
{
    <img src="{{ participant.picture }}" alt="participant.name" />
}
