// src/UI/Angular/src/Components/Ground/ground.component.ts
import { IGame, IInterfaceTexts, IItem, IBarrier } from '../../../../../Engine/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { CharacterService } from '../../../../../Engine/Services/characterService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './ground.component.html';

@Component({
    selector: 'ground',
    template: template,
})
export class GroundComponent {
    constructor(private _sharedMethodService: SharedMethodService, private _characterService: CharacterService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this._sharedMethodService.useGround = true;
    }

    game: IGame;
    texts: IInterfaceTexts;

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent(this.game);

    getCombineClass = (barrier: IBarrier): string => this.game.combinations.getCombineClass(barrier);

    pickupItem = (item: IItem): boolean => this._characterService.pickupItem(item);
}

// src/UI/Components/Exploration/Ground.vue
<template>
  <div v-if="!enemiesPresent && itemsPresent" id="exploration-onground" class="box-container">
    <div class="box-title">{{ texts.onTheGround }}</div>
    <ul class="list-unstyled">
      <li v-for="item of activeItems" :class="getCombineClass(item)" @click="pickupItem(item)">
        {{ getItemName(item) }}
      </li>
    </ul>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {IBarrier} from "storyScript/Interfaces/barrier.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {computed} from "vue";

const store = useStateStore();
const {game, useGround, enemiesPresent, activeItems} = storeToRefs(store);
const {texts, itemService} = store.services;
useGround.value = true;

const itemsPresent = computed(() => activeItems.value.length > 0);

const getCombineClass = (barrier: IBarrier): string => game.value.combinations.getCombineClass(barrier);

const getItemName = (item: IItem): string => itemService.getItemName(item);

const pickupItem = (item: IItem): boolean => itemService.pickupItem(game.value.activeCharacter, item);

</script>
