// src/UI/src/Components/LocationVisual/locationvisual.component.ts
import { IGame, IInterfaceTexts, IFeature } from '../../../../Engine/Interfaces/storyScript';
import { compareString } from '../../../../Engine/globals';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from '../../../../Engine/ObjectFactory';
import template from './locationvisual.component.html';
import { Component } from '@angular/core';

@Component({
    selector: 'location-visual',
    template: template,
})
export class LocationVisualComponent {
    constructor(private _sharedMethodService: SharedMethodService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    tryCombine = (feature: IFeature): boolean => this._sharedMethodService.tryCombine(this.game, feature);

    getFeatureCoordinates = (feature: IFeature): { top: string, left: string} => {
        var coords = feature.coords.split(',');
        var top = null, left = null;

        if (compareString(feature.shape, 'poly')) {
            var x = [], y = [];

            for (var i = 0; i < coords.length; i++) {
                var value = coords[i];
                if (i % 2 === 0) {
                    x.push(value);
                }
                else {
                    y.push(value);
                }
            }

            left = x.reduce(function (p, v) {
                return (p < v ? p : v);
            });
            
            top = y.reduce(function (p, v) {
                return (p < v ? p : v);
            });
        }
        else {
            left = coords[0];
            top = coords[1];
        }

        return { 
            top: `${top}px`,
            left: `${left}px` 
        };
    }
}
<div class="box-container" id="location-visual" *ngIf="game.currentLocation.features.collectionPicture">
    <div class="box-title" [innerHTML]="texts.format(texts.youAreHere, [game.currentLocation.name]) | safe: 'html'"></div>
    <div id="visual-features">
        <img src="{{ 'resources/' + game.currentLocation.features.collectionPicture }}" [attr.usemap]="'#' + game.currentLocation.id">
        <map name="{{ game.currentLocation.id }}">
            <area *ngFor="let feature of game.currentLocation.features" href="#0" shape="{{feature.shape}}" coords="{{feature.coords}}" (click)="tryCombine(feature)" />
        </map>
        <div *ngFor="let feature of game.currentLocation.features">
            <img *ngIf="feature.picture" class="feature-picture" name="feature.id" src="{{ 'resources/' + feature.picture }}" [ngStyle]="getFeatureCoordinates(feature)" (click)="tryCombine(feature)" />
        </div>
    </div>
</div>

// src/UI/Components/Exploration/LocationVisual.vue
<template>
  <div v-if="location?.features?.collectionPicture" id="location-visual" class="box-container">
    <div class="box-title" v-html="texts.format(texts.youAreHere, [location.name])"></div>
    <div id="visual-features">
      <img :alt="location.name" :src="`resources/${location.features.collectionPicture}`" :usemap="'#' + location.id">
      <map :name="location.id">
        <area v-for="feature of location.features" :alt="feature.name" :coords="feature.coords" :shape="feature.shape"
              href="#0" @click="combinations.tryCombine(feature)"/>
      </map>
      <div v-for="feature of location.features">
        <img v-if="feature.picture" :alt="feature.name" :name="`feature-${feature.id}`"
             :src="`resources/${feature.picture}`" :style="getFeatureCoordinates(feature)"
             class="feature-picture" @click="combinations.tryCombine(feature)"/>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {IFeature} from "storyScript/Interfaces/feature.ts";
import {compareString} from "storyScript/utilityFunctions.ts";
import {ICompiledLocation} from "storyScript/Interfaces/compiledLocation.ts";
import {IGameCombinations} from "storyScript/Interfaces/combinations/gameCombinations.ts";

const store = useStateStore();
const {texts} = store.services;

const {location, combinations} = defineProps<{
  location?: ICompiledLocation,
  combinations?: IGameCombinations
}>();

const getFeatureCoordinates = (feature: IFeature): { top: string, left: string } => {
  const coords = feature.coords.split(',');
  let top: string, left: string;

  if (compareString(feature.shape, 'poly')) {
    const x = [], y = [];

    for (let i = 0; i < coords.length; i++) {
      const value = coords[i];
      if (i % 2 === 0) {
        x.push(value);
      } else {
        y.push(value);
      }
    }

    left = x.reduce(function (p, v) {
      return (p < v ? p : v);
    });

    top = y.reduce(function (p, v) {
      return (p < v ? p : v);
    });
  } else {
    left = coords[0];
    top = coords[1];
  }

  return {
    top: `${top}px`,
    left: `${left}px`
  };
}

</script>
