// src/UserInterface/Components/Encounter/Trade.vue
<template>
  <dialog :open="playState === PlayState.Trade" class="dialog">
    <h1 v-if="trade" class="dialog-title conversation-title">
      {{ trade.name }}
    </h1>
    <div class="dialog-body conversation-body">
      <div v-if="trade" id="trade">
        <p class="trade-description">{{ trade.text }}</p>
        <div v-if="trade.buy">{{ trade.buy.text }}</div>
        <p v-if="trade.buy.items?.length === 0" class="trade-empty">{{ trade.buy.emptyText }}</p>
        <ul v-if="trade.buy.items?.length > 0 && !confirmBuyItem" class="list-unstyled">
          <li v-for="item of trade.buy.items" class="inline">
            <button type="button" class="btn btn-success" @click="buy(item, character, trade)" :disabled="!canPay(item, character, trade)">{{ displayPrice(item, actualPrice(item, character, trade)) }}</button>
          </li>
        </ul>
        
        <div v-if="confirmBuyItem">
          <p v-html="texts.format(trade.buy.confirmationText, [confirmBuyItem.name, actualPrice(confirmBuyItem, character, trade).toString(), texts.currency])"></p>
          <ul class="list-unstyled">
            <li class="inline">
              <button type="button" class="btn btn-primary" @click="cancelBuy()">{{ texts.cancelBuy }}</button>
              <button type="button" class="btn btn-warning" @click="buy(confirmBuyItem, character, trade)">{{ texts.confirmBuy }}</button>
            </li>
          </ul>
        </div>
        
        <div v-if="trade.sell">{{ trade.sell.text }}</div>
        
        <p v-if="trade.sell.items?.length === 0" class="trade-empty">{{ trade.sell.emptyText }}</p>


        <ul v-if="trade.sell.items?.length > 0 && !confirmSellItem" class="list-unstyled">
          <li v-for="item of trade.sell.items" class="inline">
            <button type="button" class="btn btn-warning" @click="sell(item, trade, character)" :disabled="!canPay(item, trade, character)">{{ displayPrice(item, actualPrice(item, trade, character)) }}</button>
          </li>
        </ul>
        
        <div v-if="confirmSellItem">
          <p v-html="texts.format(trade.sell.confirmationText, [confirmSellItem.name, actualPrice(confirmSellItem, trade, character).toString(), texts.currency])"></p>
          <ul class="list-unstyled">
            <li class="inline">
              <button type="button" class="btn btn-primary" @click="cancelSell()">{{ texts.cancelSell }}</button>
              <button type="button" class="btn btn-warning" @click="sell(confirmSellItem, trade, character)">{{ texts.confirmSell }}</button>
            </li>
          </ul>
        </div>
        
        <p v-if="trade.currency != undefined">{{ texts.format(texts.traderCurrency, [trade.currency.toString(), texts.currency]) }}</p>
      </div>
    </div>
  </dialog>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {PlayState} from "storyScript/Interfaces/enumerations/playState.ts";
import {ITrade} from "storyScript/Interfaces/trade.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {ref} from "vue";

const store = useStateStore();
const {texts, tradeService} = store.services;

const { playState, trade, character } = defineProps<{
  trade?: ITrade,
  playState?: PlayState,
  character?: ICharacter
}>();

const confirmBuyItem = ref<IItem>(null);
const confirmSellItem= ref<IItem>(null);

const canPay = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => tradeService.canPay(item, buyer, seller);

const actualPrice = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): number => tradeService.actualPrice(item, buyer, seller);

const displayPrice = (item: IItem, actualPrice: number): string => tradeService.displayPrice(item, actualPrice);

const cancelBuy = (): void => confirmBuyItem.value = undefined;

const buy = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => {
  if (actualPrice(item, buyer, seller) > 0 && !confirmBuyItem) {
    confirmBuyItem.value = item;
    return true;
  }

  confirmBuyItem.value = undefined;
  return tradeService.buy(item, seller);
}

const cancelSell = (): void => confirmSellItem.value = undefined;

const sell = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => {
  if (actualPrice(item, buyer, seller) > 0 && !confirmSellItem) {
    confirmSellItem.value = item;
    return true;
  }

  confirmSellItem.value = undefined;
  return tradeService.sell(item, buyer);
}

</script>

// src/UI/src/Components/Trade/trade.component.ts
import { IGame, IInterfaceTexts, IItem, ITrade } from '../../../../Engine/Interfaces/storyScript';
import { TradeService } from '../../../../Engine/Services/TradeService';
import { ObjectFactory } from '../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './trade.component.html';

@Component({
    selector: 'trade',
    template: template,
})
export class TradeComponent {
    constructor(private _tradeService: TradeService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    canPay = (currency: number, value: number): boolean => {
        return this._tradeService.canPay(currency, value);
    }

    actualPrice = (item: IItem, modifier: number | (() => number)): number => this._tradeService.actualPrice(item, modifier);

    displayPrice = (item: IItem, actualPrice: number): string  => this._tradeService.displayPrice(item, actualPrice);

    buy = (item: IItem, trade: ITrade): boolean => this._tradeService.buy(item, trade);
    
    sell = (item: IItem, trade: ITrade): boolean => this._tradeService.sell(item, trade);
}
<div *ngIf="game.playState == 'Trade' && game.trade" id="trade">
    <p class="trade-description">{{ game.trade.description }}</p>
    <div *ngIf="game.trade.buy">{{ game.trade.buy.description }}</div>
    <p class="trade-empty" *ngIf="!game.trade.buy.items || !game.trade.buy.items.length === 0">{{ game.trade.buy.emptyText }}</p>
    <ul class="list-unstyled" *ngIf="game.trade.buy.items && game.trade.buy.items.length > 0">
        <li class="inline" *ngFor="let item of game.trade.buy.items">
            <button type="button" class="btn btn-success" (click)="buy(item, game.trade)" [disabled]="!canPay(game.character.currency, actualPrice(item, game.trade.buy.priceModifier))">{{ displayPrice(item, game.trade.buy.priceModifier) }}</button>
        </li>
    </ul>
    <div *ngIf="game.trade.sell">{{ game.trade.sell.description }}</div>
    <p class="trade-empty" *ngIf="!game.trade.sell.items || game.trade.sell.items.length === 0">{{ game.trade.sell.emptyText }}</p>
    <ul class="list-unstyled" *ngIf="game.trade.sell.items && game.trade.sell.items.length > 0">
        <li class="inline" *ngFor="let item of game.trade.sell.items">
            <button type="button" class="btn btn-warning" (click)="sell(item, game.trade)" [disabled]="!canPay(game.trade.currency, actualPrice(item, game.trade.sell.priceModifier))">{{ displayPrice(item, game.trade.sell.priceModifier) }}</button>
        </li>
    </ul>
    <p *ngIf="game.trade.currency != undefined">{{ texts.format(texts.traderCurrency, [game.trade.currency, texts.currency]) }}</p>
</div>
