// src/UI/Components/Exploration/Ground.vue
<template>
  <div v-if="!enemiesPresent(game) && items?.length" id="exploration-onground" class="box-container">
    <div class="box-title">{{ texts.onTheGround }}</div>
    <ul class="list-unstyled">
      <li v-for="item of items" :class="getCombineClass(item)" @click="pickupItem(item)">
        {{ getItemName(item) }}
      </li>
    </ul>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {enemiesPresent} from "ui/Helpers.ts";
import {IBarrier} from "storyScript/Interfaces/barrier.ts";
import {IItem} from "storyScript/Interfaces/item.ts";

const store = useStateStore();
const {game, useGround} = storeToRefs(store);
const {texts, itemService} = store.services;

const { items } = defineProps<{
  items?: IItem[]
}>();

useGround.value = true;

const getCombineClass = (barrier: IBarrier): string => game.value.combinations.getCombineClass(barrier);

const getItemName = (item: IItem): string => itemService.getItemName(item);

const pickupItem = (item: IItem): boolean => itemService.pickupItem(game.value.activeCharacter, item);

</script>

// src/UI/Components/Ground/ground.component.ts
import {IBarrier, IGame, IInterfaceTexts, IItem} from 'storyScript/Interfaces/storyScript';
import {SharedMethodService} from '../../Services/SharedMethodService';
import {ServiceFactory} from 'storyScript/ServiceFactory.ts';
import {Component, inject} from '@angular/core';
import {getTemplate} from '../../helpers';
import {ItemService} from "storyScript/Services/ItemService.ts";

@Component({
    selector: 'ground',
    template: getTemplate('ground', await import('./ground.component.html?raw'))
})
export class GroundComponent {
    private _sharedMethodService: SharedMethodService;
    private _itemService: ItemService;

    constructor() {
        this._sharedMethodService = inject(SharedMethodService);
        this._itemService = inject(ItemService);
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this._sharedMethodService.useGround = true;
    }

    game: IGame;
    texts: IInterfaceTexts;

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent();

    getCombineClass = (barrier: IBarrier): string => this.game.combinations.getCombineClass(barrier);

    getItemName = (item: IItem): string => this._itemService.getItemName(item);

    pickupItem = (item: IItem): boolean => this._itemService.pickupItem(this.game.activeCharacter, item);
}
@let items = game.currentLocation.activeItems;
@if (!enemiesPresent() && items.length)
{
    <div class="box-container" id="exploration-onground">
        <div class="box-title">{{ texts.onTheGround }}</div>
        <ul class="list-unstyled">
            @for (item of items; track item.id)
            {
                <li (click)="pickupItem(item)" [ngClass]="getCombineClass(item)">
                    {{ getItemName(item) }}
                </li>
            }
        </ul>
    </div>
}
