// src/UI/Components/Party/CreateCharacter.vue
<template>
  <div v-if="game.state === 'CreateCharacter'" id="create-character" class="box-container">
    <div class="box-title">{{ titleText() }}</div>
    <build-character :sheet="game.createCharacterSheet"></build-character>
    <button
        v-if="game.createCharacterSheet.currentStep >= game.createCharacterSheet.steps.length - 1 || game.createCharacterSheet.steps[game.createCharacterSheet.currentStep].finish"
        id="start-adventure" :disabled="!characterService.distributionDone(game.createCharacterSheet, null)"
        class="btn btn-primary" type="button"
        @click="gameService.startNewGame(game.createCharacterSheet)">{{ startText() }}
    </button>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, rules, characterService, gameService} = store.services;

const titleText = (): string => {
  if (rules.setup.numberOfCharacters > 1) {
    switch (game.value.party.characters.length || 0) {
      case 0:
        return texts.firstCharacter;
      case 1:
        return texts.secondCharacter;
      case 2:
        return texts.thirdCharacter;
      default:
        return texts.format(texts.nthCharacter, [(game.value.party.characters.length + 1).toString()])
    }
  }

  return texts.newGame;
};

const startText = (): string => {
  if (rules.setup.numberOfCharacters > 1 && (game.value.party.characters.length < rules.setup.numberOfCharacters - 1)) {
    return texts.nextCharacter;
  }

  return texts.startAdventure;
};

</script>

// src/UI/Angular/src/Components/CreateCharacter/createcharacter.component.ts
import { IGame, IInterfaceTexts, CreateCharacters } from '../../../../../Engine/Interfaces/storyScript';
import { GameService } from '../../../../../Engine/Services/gameService';
import { CharacterService } from '../../../../../Engine/Services/characterService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './createcharacter.component.html';

@Component({
    selector: 'create-character',
    template: template,
})
export class CreateCharacterComponent {
    constructor(private _characterService: CharacterService, private _gameService: GameService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    startNewGame = () => this._gameService.startNewGame(this.game.createCharacterSheet);

    distributionDone = (step: CreateCharacters.ICreateCharacterStep): boolean => this._characterService.distributionDone(this.game.createCharacterSheet, step);
}
<div class="box-container" id="create-character" *ngIf="game.state === 'CreateCharacter'">
    <div class="box-title">{{ texts.newGame }}</div>
    <buildcharacter [sheet]="game.createCharacterSheet"></buildcharacter>
    <button type="button" id="start-adventure" class="btn btn-primary" [disabled]="!distributionDone()" (click)="startNewGame()" *ngIf="game.createCharacterSheet.currentStep >= game.createCharacterSheet.steps.length - 1 || game.createCharacterSheet.steps[game.createCharacterSheet.currentStep].finish">{{ texts.startAdventure }}</button>
</div>
