// src/UI/Components/GameOver/gameover.component.ts
import { IGame, IInterfaceTexts } from 'storyScript/Interfaces/storyScript';
import { GameService } from 'storyScript/Services/gameService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component } from '@angular/core';
import template from './gameover.component.html';

@Component({
    selector: 'game-over',
    template: template,
})
export class GameOverComponent {
    constructor(private _gameService: GameService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    restart = (): void => this._gameService.restart();
}
@if (game.state === 'GameOver')
{
    <div class="container-fluid">
        <div class="col-12">
            <h2>{{ texts.youLost }}</h2>
            <p>{{ texts.questFailed }}</p>
            <div>{{ texts.finalScore }}{{ game.party.score }}</div>
            <button type="button" class="btn btn-primary restart" (click)="restart()">{{ texts.tryAgain }}</button>
            <highscores></highscores>
        </div>
    </div>
}

// src/UserInterface/Components/GameState/GameOver.vue
<template>
  <div class="container-fluid">
    <div class="col-12">
      <h2>{{ texts.youLost }}</h2>
      <p>{{ texts.questFailed }}</p>
      <div>{{ texts.finalScore }}{{ score }}</div>
      <button class="btn btn-primary restart" type="button" @click="restart()">{{ texts.tryAgain }}</button>
      <high-scores v-if="score > 0" :scores="game.highScores"></high-scores>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, gameService} = store.services;

const {score} = defineProps<{
  score: number;
}>();

const restart = (): void => gameService.restart();

</script>
