// src/UI/Components/Victory/victory.component.ts
import { IGame, IInterfaceTexts } from 'storyScript/Interfaces/storyScript';
import { GameService } from 'storyScript/Services/gameService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component } from '@angular/core';
import template from './victory.component.html';

@Component({
    selector: 'victory',
    template: template,
})
export class VictoryComponent {
    constructor(private _gameService: GameService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    restart = (): void => this._gameService.restart();
}
@if (game.state === 'Victory')
{
    <div class="container-fluid">
        <div class="col-12">
            <h1>{{ texts.youWon }}</h1>
            <div><span>{{ texts.congratulations }}</span></div>
            <div><span>{{ texts.finalScore }}{{ game.party.score }}</span></div>
            <button type="button" class="btn btn-primary" (click)="restart()">{{ texts.playAgain }}</button>
            <highscores></highscores>
        </div>
    </div>
}

// src/UserInterface/Components/GameState/Victory.vue
<template>
  <div class="container-fluid">
    <div class="col-12">
      <h1>{{ texts.youWon }}</h1>
      <div><span>{{ texts.congratulations }}</span></div>
      <div><span>{{ texts.finalScore }}{{ score }}</span></div>
      <button class="btn btn-primary" type="button" @click="restart()">{{ texts.playAgain }}</button>
      <high-scores v-if="score > 0" :scores="game.highScores"></high-scores>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, gameService} = store.services;

const {score} = defineProps<{
  score?: number;
}>();

const restart = (): void => gameService.restart();

</script>
