// src/UI/Components/LocationText/locationtext.component.ts
import { IGame, IInterfaceTexts, IFeature } from 'storyScript/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component, Inject } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'location-text',
    template: getTemplate('locationtext', await import('./locationtext.component.html'))
})
export class LocationTextComponent {
    constructor(
        @Inject (SharedMethodService) private _sharedMethodService: SharedMethodService, 
        @Inject (ObjectFactory) objectFactory: ObjectFactory
    ) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this.worldProperties = [];

        this.initWorldProperties();
    }

    game: IGame;
    texts: IInterfaceTexts;
    worldProperties: { name: string, value: string }[];

    tryCombine = (feature: IFeature): boolean => this._sharedMethodService.tryCombine(feature);

    private initWorldProperties = (): void => {
        for (var n in this.game.worldProperties) {
            if (this.game.worldProperties.hasOwnProperty(n) && this.texts.worldProperties && this.texts.worldProperties.hasOwnProperty(n)) {
                var value = this.texts.worldProperties[n];
                this.worldProperties.push({ name: n, value: value});
            }
        }
    }
}
@let location = game.currentLocation;
@if (location.description || !location.features?.collectionPicture) 
{
    <div class="box-container" id="location">
        <div class="box-title" [innerHTML]="texts.format(texts.youAreHere, [location.name]) | safe: 'html'"></div>
        <div textFeatures>
            <div [innerHTML]="location.description | safe: 'html'"></div>
        </div>
        <ul id="location-log" class="list-unstyled">
            @for (message of location.log; track $index)
            {
                <li [innerHTML]="message | safe: 'html'"></li>
            }
        </ul>
    </div>
}

// src/UserInterface/Components/LocationText.vue
<template>
  <div v-if="show()" class="box-container" id="location">
    <div class="box-title" v-html="texts.format(texts.youAreHere, [game.currentLocation.name])"></div>
    <div textFeatures>
      <div v-html="game.currentLocation.description"></div>
    </div>
    <ul id="location-log" class="list-unstyled">
      <li v-for="message in game.currentLocation.log" v-html="message"></li>
    </ul>
  </div>
</template>
<script lang="ts" setup>
  import {computed} from "@angular/core";
  import {useStateStore} from "vue/StateStore.ts";
  import {storeToRefs} from "pinia";

  const store = useStateStore();
  const {game, texts} = storeToRefs(store);
  
  const show = computed(() => game.value.currentLocation.description || !game.value.currentLocation.features?.collectionPicture);
</script>
