// src/UI/Components/Sound/sound.component.ts
import {Component, inject} from '@angular/core';
import {IGame} from 'storyScript/Interfaces/game';
import {ServiceFactory} from 'storyScript/ServiceFactory.ts';
import {getTemplate} from '../../helpers';
import {IRules} from 'storyScript/Interfaces/storyScript';
import {SoundService} from "storyScript/Services/SoundService.ts";
import {SharedModule} from "ui/Modules/sharedModule.ts";

@Component({
    standalone: true,
    selector: 'sound',
    imports: [SharedModule],
    template: getTemplate('sound', await import('./sound.component.html?raw'))
})
export class SoundComponent {
    private readonly _soundService: SoundService;

    private readonly _game: IGame;
    private readonly _rules: IRules;
    private _isPlaying: boolean = false;
    private _fadeInterval: NodeJS.Timeout;
    private _fadingMusic: boolean = false;
    private _currentMusic: string;
    private _currentVolume: number = 1;
    private readonly _soundQueue: [number, string][] = [];

    constructor() {
        this._soundService = inject(SoundService);
        const objectFactory = inject(ServiceFactory);
        this._game = objectFactory.GetGame();
        this._rules = objectFactory.GetRules();
        setInterval(this.checkMusicPlaying, 500);
    }

    getCurrentMusic = (): string => {
        const music = this._soundService.getCurrentMusic();

        if (this._rules.setup.fadeMusicInterval) {

            if (!this._currentMusic) {
                this._currentMusic = music;
            }

            if (!this._fadingMusic && music != this._currentMusic) {
                this._fadingMusic = true;
                this._fadeInterval = setInterval(() => this.fade(music), this._rules.setup.fadeMusicInterval);
            }

            return this._currentMusic;
        }

        return music;
    }

    getSoundQueue = (): [number, string][] => {
        Array.from(this._game.sounds.soundQueue).forEach(e => {
            if (!e[1].playing) {
                this._soundQueue.push([e[0], e[1].value]);
                e[1].playing = true;
            }
        });

        return this._soundQueue;
    }

    soundCompleted = (soundKey: number) => {
        this._game.sounds.soundQueue.get(soundKey).completeCallBack?.();
        this._game.sounds.soundQueue.delete(soundKey);
        const index = this._soundQueue.indexOf(this._soundQueue.find(([k, _]) => soundKey === k));

        if (index > -1) {
            this._soundQueue.splice(index, 1);
        }
    }

    // This code is here to (re)start music playback as soon as the user interacts with the browser.
    private readonly checkMusicPlaying = () => {
        if (this._isPlaying) {
            return;
        }

        const backgroundMusicElement = this.getMusicPlayer();

        if (backgroundMusicElement) {
            // This will trigger a warning when the user hasn't interacted with the web page yet. Currently (June 1st 2023),
            // I haven't found a way to silence this warning.
            const audioContext = new window.AudioContext();

            if (audioContext?.state !== 'suspended') {
                backgroundMusicElement.play();
                this._isPlaying = true;
            }
        }
    }

    private readonly fade = (newMusic: string) => {
        const newVolume = this._currentVolume - 0.1;

        if (newVolume >= 0) {
            this._currentVolume = newVolume;
        } else {
            clearInterval(this._fadeInterval);
            this._currentVolume = 1;
            this._currentMusic = newMusic;
            this._fadingMusic = false;
        }

        const backgroundMusicElement = this.getMusicPlayer();
        backgroundMusicElement.volume = this._currentVolume;
    }

    private readonly getMusicPlayer = () => {
        return <HTMLAudioElement>this._game.UIRootElement.getElementsByClassName('backgroundmusic-player')[0];
    }
}
@if (getCurrentMusic())
{
    <audio class="storyscript-player backgroundmusic-player" src="resources/{{ getCurrentMusic() }}" autoplay loop></audio>
}
@for (sound of getSoundQueue(); track sound)
{
    <audio class="storyscript-player" src="resources/{{ sound[1] }}" autoplay (ended)="soundCompleted(sound[0])"></audio>
}

// src/UserInterface/Components/Sound.vue
<template>
  <audio v-if="getCurrentMusic()" autoplay
         class="storyscript-player backgroundmusic-player" loop :src="`resources/${getCurrentMusic()}`"></audio>
  <audio v-for="sound of getSoundQueue()" autoplay class="storyscript-player" src="resources/{{ sound[1] }}"
         @ended="soundCompleted(sound[0])"></audio>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {ref} from "vue";

const store = useStateStore();
const {game, rules} = storeToRefs(store);

const isPlaying = ref(false);
const fadeInterval = ref<NodeJS.Timeout>(null);
const fadingMusic = ref(false);
const currentMusic = ref<string>(null);
const currentVolume = ref(1);
const soundQueue: [number, string][] = [];

// This code is here to (re)start music playback as soon as the user interacts with the browser.
const checkMusicPlaying = () => {
  if (isPlaying) {
    return;
  }

  const backgroundMusicElement = getMusicPlayer();

  if (backgroundMusicElement) {
    // This will trigger a warning when the user hasn't interacted with the web page yet. Currently (June 1st 2023),
    // I haven't found a way to silence this warning.
    const audioContext = new window.AudioContext();

    if (audioContext?.state !== 'suspended') {
      backgroundMusicElement.play();
      isPlaying.value = true;
    }
  }
}

setInterval(checkMusicPlaying, 500);

const getCurrentMusic = (): string => {
  const music = store.getSoundService().getCurrentMusic();

  if (rules.value.setup.fadeMusicInterval) {

    if (!currentMusic) {
      currentMusic.value = music;
    }

    if (!fadingMusic && music != currentMusic.value) {
      fadingMusic.value = true;
      fadeInterval.value = setInterval(() => fade(music), rules.value.setup.fadeMusicInterval);
    }

    return currentMusic.value;
  }

  return music;
}

const getSoundQueue = (): [number, string][] => {
  Array.from(game.value.sounds.soundQueue).forEach(e => {
    if (!e[1].playing) {
      soundQueue.push([e[0], e[1].value]);
      e[1].playing = true;
    }
  });

  return soundQueue;
}

const soundCompleted = (soundKey: number) => {
  game.value.sounds.soundQueue.get(soundKey).completeCallBack?.();
  game.value.sounds.soundQueue.delete(soundKey);
  const index = soundQueue.indexOf(soundQueue.find(([k, _]) => soundKey === k));

  if (index > -1) {
    soundQueue.splice(index, 1);
  }
}

const fade = (newMusic: string) => {
  const newVolume = currentVolume.value - 0.1;

  if (newVolume >= 0) {
    currentVolume.value = newVolume;
  } else {
    clearInterval(fadeInterval.value);
    currentVolume.value = 1;
    currentMusic.value = newMusic;
    fadingMusic.value = false;
  }

  const backgroundMusicElement = getMusicPlayer();
  backgroundMusicElement.volume = currentVolume.value;
}

const getMusicPlayer = () => {
  return <HTMLAudioElement>game.value.UIRootElement.getElementsByClassName('backgroundmusic-player')[0];
}

</script>
