// src/UI/Components/Trade/trade.component.ts
import {ICharacter, IGame, IInterfaceTexts, IItem, ITrade} from 'storyScript/Interfaces/storyScript';
import { TradeService } from 'storyScript/Services/TradeService';
import { ServiceFactory } from 'storyScript/ServiceFactory.ts';
import { Component, inject } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'trade',
    template: getTemplate('trade', await import('./trade.component.html?raw'))
})
export class TradeComponent {
    private _tradeService: TradeService;
    
    constructor() {
        this._tradeService = inject(TradeService);
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;
    confirmBuyItem: IItem;
    confirmSellItem: IItem;

    canPay = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => this._tradeService.canPay(item, buyer, seller);

    actualPrice = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): number => this._tradeService.actualPrice(item, buyer, seller);

    displayPrice = (item: IItem, actualPrice: number): string  => this._tradeService.displayPrice(item, actualPrice);

    cancelBuy = (): void => this.confirmBuyItem = undefined;
    
    buy = (item: IItem, trade: ITrade): boolean => {
        if (item.value > 0 && !this.confirmBuyItem) {
            this.confirmBuyItem = item;
            return true;
        }

        this.confirmBuyItem = undefined;
        return this._tradeService.buy(item, trade); 
    }

    cancelSell = (): void => this.confirmSellItem = undefined;
    
    sell = (item: IItem, trade: ITrade): boolean => {
        if (item.value > 0 && !this.confirmSellItem) {
            this.confirmSellItem = item;
            return true;
        }

        this.confirmSellItem = undefined;
        return this._tradeService.sell(item, trade);
    }
}
@let trade = game.trade;
<div *ngIf="game.playState == 'Trade' && trade" id="trade">
    <p class="trade-description">{{ trade.text }}</p>
    <div *ngIf="trade.buy">{{ trade.buy.text }}</div>
    <p class="trade-empty" *ngIf="trade.buy.items?.length === 0">{{ trade.buy.emptyText }}</p>
    <ul class="list-unstyled" *ngIf="trade.buy.items?.length > 0 && !confirmBuyItem">
        <li class="inline" *ngFor="let item of trade.buy.items">
            <button type="button" class="btn btn-success" (click)="buy(item, trade)" [disabled]="!canPay(item, game.activeCharacter, game.party.currency, actualPrice(item, trade.buy.priceModifier))">{{ displayPrice(item, trade.buy.priceModifier) }}</button>
        </li>
    </ul>
    <div *ngIf="confirmBuyItem">
        <p [innerHTML]="texts.format(trade.buy.confirmationText, [confirmBuyItem.name, actualPrice(confirmBuyItem, trade.buy.priceModifier), texts.currency]) | safe: 'html'"></p>
        <ul class="list-unstyled">
            <li class="inline">
                <button type="button" class="btn btn-primary" (click)="cancelBuy()">{{ texts.cancelBuy }}</button>
                <button type="button" class="btn btn-warning" (click)="buy(confirmBuyItem, trade)">{{ texts.confirmBuy }}</button>
            </li>
        </ul>
    </div>
    <div *ngIf="trade.sell">{{ trade.sell.text }}</div>
    <p class="trade-empty" *ngIf="trade.sell.items?.length === 0">{{ trade.sell.emptyText }}</p>
    <ul class="list-unstyled" *ngIf="trade.sell.items?.length > 0 && !confirmSellItem">
        <li class="inline" *ngFor="let item of trade.sell.items">
            <button type="button" class="btn btn-warning" (click)="sell(item, trade)" [disabled]="!canPay(item, trade, trade.currency, actualPrice(item, trade.sell.priceModifier))">{{ displayPrice(item, trade.sell.priceModifier) }}</button>
        </li>
    </ul>
    <div *ngIf="confirmSellItem">
        <p [innerHTML]="texts.format(trade.sell.confirmationText, [confirmSellItem.name, actualPrice(confirmSellItem, trade.sell.priceModifier), texts.currency]) | safe: 'html'"></p>
        <ul class="list-unstyled">
            <li class="inline">
                <button type="button" class="btn btn-primary" (click)="cancelSell()">{{ texts.cancelSell }}</button>
                <button type="button" class="btn btn-warning" (click)="buy(confirmSellItem, trade)">{{ texts.confirmSell }}</button>
            </li>
        </ul>
    </div>
    <p *ngIf="trade.currency != undefined">{{ texts.format(texts.traderCurrency, [trade.currency, texts.currency]) }}</p>
</div>

// src/UserInterface/Components/Trade.vue
<template>
  <dialog :open="playState === PlayState.Trade" class="dialog">
    <h1 v-if="trade" class="dialog-title conversation-title">
      {{ trade.name }}
    </h1>
    <div class="dialog-body conversation-body">
      <div v-if="trade" id="trade">
        <p class="trade-description">{{ trade.text }}</p>
        <div v-if="trade.buy">{{ trade.buy.text }}</div>
        <p v-if="trade.buy.items?.length === 0" class="trade-empty">{{ trade.buy.emptyText }}</p>
        <ul v-if="trade.buy.items?.length > 0 && !confirmBuyItem" class="list-unstyled">
          <li v-for="item of trade.buy.items" class="inline">
            <button type="button" class="btn btn-success" @click="buy(item, character, trade)" :disabled="!canPay(item, character, trade)">{{ displayPrice(item, actualPrice(item, character, trade)) }}</button>
          </li>
        </ul>
        
        <div v-if="confirmBuyItem">
          <p v-html="texts.format(trade.buy.confirmationText, [confirmBuyItem.name, actualPrice(confirmBuyItem, character, trade).toString(), texts.currency])"></p>
          <ul class="list-unstyled">
            <li class="inline">
              <button type="button" class="btn btn-primary" @click="cancelBuy()">{{ texts.cancelBuy }}</button>
              <button type="button" class="btn btn-warning" @click="buy(confirmBuyItem, character, trade)">{{ texts.confirmBuy }}</button>
            </li>
          </ul>
        </div>
        
        <div v-if="trade.sell">{{ trade.sell.text }}</div>
        
        <p v-if="trade.sell.items?.length === 0" class="trade-empty">{{ trade.sell.emptyText }}</p>


        <ul v-if="trade.sell.items?.length > 0 && !confirmSellItem" class="list-unstyled">
          <li v-for="item of trade.sell.items" class="inline">
            <button type="button" class="btn btn-warning" @click="sell(item, trade, character)" :disabled="!canPay(item, trade, character)">{{ displayPrice(item, actualPrice(item, trade, character)) }}</button>
          </li>
        </ul>
        
        <div v-if="confirmSellItem">
          <p v-html="texts.format(trade.sell.confirmationText, [confirmSellItem.name, actualPrice(confirmSellItem, trade, character).toString(), texts.currency])"></p>
          <ul class="list-unstyled">
            <li class="inline">
              <button type="button" class="btn btn-primary" @click="cancelSell()">{{ texts.cancelSell }}</button>
              <button type="button" class="btn btn-warning" @click="sell(confirmSellItem, trade, character)">{{ texts.confirmSell }}</button>
            </li>
          </ul>
        </div>
        
        <p v-if="trade.currency != undefined">{{ texts.format(texts.traderCurrency, [trade.currency.toString(), texts.currency]) }}</p>
      </div>
    </div>
  </dialog>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {PlayState} from "storyScript/Interfaces/enumerations/playState.ts";
import {ITrade} from "storyScript/Interfaces/trade.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {ref} from "vue";
import {useServices} from "vue/Services.ts";

const store = useStateStore();
const {texts} = storeToRefs(store);
const tradeService = useServices().getTradeService();

const { playState, trade, character } = defineProps<{
  trade?: ITrade,
  playState?: PlayState,
  character?: ICharacter
}>();

const confirmBuyItem = ref<IItem>(null);
const confirmSellItem= ref<IItem>(null);

const canPay = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => tradeService.canPay(item, buyer, seller);

const actualPrice = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): number => tradeService.actualPrice(item, buyer, seller);

const displayPrice = (item: IItem, actualPrice: number): string => tradeService.displayPrice(item, actualPrice);

const cancelBuy = (): void => confirmBuyItem.value = undefined;

const buy = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => {
  if (actualPrice(item, buyer, seller) > 0 && !confirmBuyItem) {
    confirmBuyItem.value = item;
    return true;
  }

  confirmBuyItem.value = undefined;
  return tradeService.buy(item, seller);
}

const cancelSell = (): void => confirmSellItem.value = undefined;

const sell = (item: IItem, buyer: ITrade | ICharacter, seller: ITrade | ICharacter): boolean => {
  if (actualPrice(item, buyer, seller) > 0 && !confirmSellItem) {
    confirmSellItem.value = item;
    return true;
  }

  confirmSellItem.value = undefined;
  return tradeService.sell(item, buyer);
}

</script>
