// src/UserInterface/Components/Party/CreateCharacter.vue
<template>
  <div v-if="state === 'CreateCharacter'" class="box-container" id="create-character">
    <div class="box-title">{{ titleText() }}</div>
    <build-character :sheet="sheet"></build-character>
    <button v-if="sheet.currentStep >= sheet.steps.length - 1 || sheet.steps[sheet.currentStep].finish" type="button" id="start-adventure" class="btn btn-primary" :disabled="!distributionDone()" @click="startNewGame()">{{ startText() }}</button>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {IParty} from "storyScript/Interfaces/party.ts";
import {ICreateCharacter} from "storyScript/Interfaces/createCharacter/createCharacter.ts";
import {GameState} from "storyScript/Interfaces/enumerations/gameState.ts";

const store = useStateStore();
const {texts, rules, characterService, gameService} = store.services;

const { state, party, sheet } = defineProps<{
  state: GameState;
  party?: IParty,
  sheet?: ICreateCharacter
}>();

const titleText = (): string => {
  if (rules.setup.numberOfCharacters > 1) {
    switch (party.characters.length || 0) {
      case 0:
        return texts.firstCharacter;
      case 1:
        return texts.secondCharacter;
      case 2:
        return texts.thirdCharacter;
      default:
        return texts.format(texts.nthCharacter, [(party.characters.length + 1).toString()])
    }
  }

  return texts.newGame;
};

const startText = (): string => {
  if (rules.setup.numberOfCharacters > 1 && (party.characters.length < rules.setup.numberOfCharacters - 1)) {
    return texts.nextCharacter;
  }

  return texts.startAdventure;
};

const distributionDone = (): boolean => characterService.distributionDone(sheet, null);

const startNewGame = () => gameService.startNewGame(sheet);

</script>

// src/UI/Components/CreateCharacter/createcharacter.component.ts
import { IGame, IInterfaceTexts, ICreateCharacterStep, IRules } from 'storyScript/Interfaces/storyScript';
import { GameService } from 'storyScript/Services/gameService';
import { CharacterService } from 'storyScript/Services/characterService';
import { ServiceFactory } from 'storyScript/ServiceFactory.ts';
import { Component, inject } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'create-character',
    template: getTemplate('createcharacter', await import('./createcharacter.component.html'))
})
export class CreateCharacterComponent {
    private _characterService: CharacterService;
    private _gameService: GameService;
    private _rules: IRules;

    constructor() {
        this._characterService = inject(CharacterService);
        this._gameService = inject(GameService);
        const objectFactory = inject(ServiceFactory);
        this._rules = objectFactory.GetRules();
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    titleText: string;
    startText: string;
    game: IGame;
    texts: IInterfaceTexts;

    startNewGame = () => {
        this._gameService.startNewGame(this.game.createCharacterSheet);
    }

    distributionDone = (step: ICreateCharacterStep): boolean => this._characterService.distributionDone(this.game.createCharacterSheet, step);

    getTitleText = () => {
        if (this._rules.setup.numberOfCharacters > 1) {
            switch (this.game.party?.characters.length || 0) {
                case 0: return this.texts.firstCharacter;
                case 1: return this.texts.secondCharacter;
                case 2: return this.texts.thirdCharacter;
                default: return this.texts.format(this.texts.nthCharacter, [(this.game.party.characters.length + 1).toString()])
            }
        }

        return this.texts.newGame;
    }

    getStartText = () => { 
        if (this._rules.setup.numberOfCharacters > 1 && (!this.game.party || this.game.party?.characters.length < this._rules.setup.numberOfCharacters - 1)) {
            return this.texts.nextCharacter;
        }

        return this.texts.startAdventure;
    }
}
<div class="box-container" id="create-character" *ngIf="game.state === 'CreateCharacter'">
    <div class="box-title">{{ texts.newGame }}</div>
    <build-character [sheet]="game.createCharacterSheet"></build-character>
    <button type="button" id="start-adventure" class="btn btn-primary" [disabled]="!distributionDone()" (click)="startNewGame()" *ngIf="game.createCharacterSheet.currentStep >= game.createCharacterSheet.steps.length - 1 || game.createCharacterSheet.steps[game.createCharacterSheet.currentStep].finish">{{ texts.startAdventure }}</button>
</div>
