// src/UI/Components/Navigation.vue
<template>
  <div class="container-fluid menu-bar">
    <div class="row">
      <div class="col-8">
        <h1>{{ texts.gameName }}</h1>
      </div>
      <div class="col-4">
<!--        @if (isDevelopment && locations.length > 1)-->
<!--        {-->
<!--        <input-->
<!--            id="location-selector"-->
<!--            type="text"-->
<!--            class="form-control"-->
<!--            [(ngModel)]="model"-->
<!--            [ngbTypeahead]="search"-->
<!--            [inputFormatter]="formatter"-->
<!--            [resultFormatter]="formatter"-->
<!--            [editable]="false"-->
<!--            placeholder="Jump to location..."-->
<!--            (focus)="focus$.next($any($event).target.value)"-->
<!--            (click)="click$.next($any($event).target.value)"-->
<!--            (selectItem)="jumpToLocation($event)"-->
<!--            #instance="ngbTypeahead"-->
<!--        />-->
<!--        }-->
        <div class="float-right">
          <button type="button" class="btn btn-dark btn-sm" @click="menu()">{{ texts.mainMenuShort }}</button>
          <button v-if="isDevelopment" id="resetbutton" type="button" class="btn btn-danger btn-sm" @click="reset()">{{ texts.resetWorld }}</button>
        </div>
        <div class="float-none"></div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {PlayState} from "storyScript/Interfaces/enumerations/playState.ts";
import {isDevelopment} from "ui/Helpers.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, gameService} = store.services;

const menu = () => game.value.playState = PlayState.Menu;

const reset = () => gameService.reset();

</script>

// src/UI/Angular/src/Components/Navigation/navigation.component.ts
import { IGame, IInterfaceTexts, Enumerations } from '../../../../../Engine/Interfaces/storyScript';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import template from './navigation.component.html';
import { Component } from '@angular/core';
import { GameService } from '../../../../../Engine/Services/gameService';

@Component({
    selector: 'navigation',
    template: template,
})
export class NavigationComponent {
    constructor(private _gameService: GameService, private _objectFactory: ObjectFactory) {
        this.game = _objectFactory.GetGame();
        this.texts = _objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    menu = (): Enumerations.PlayState => this.game.playState = Enumerations.PlayState.Menu;

    reset = (): void => this._gameService.reset();
}
<div class="container-fluid menu-bar">
    <div class="row">
        <div class="col-8">
            <h1>{{ texts.gameName }}</h1>
        </div>
        <div class="col-4">
            <div class="float-right">
                <button type="button" class="btn btn-dark btn-sm" (click)="menu()">{{ texts.mainMenuShort }}</button>
                <button id="resetbutton" type="button" class="btn btn-danger btn-sm" (click)="reset()">{{ texts.resetWorld }}</button>
            </div>
            <div class="float-none"></div>
        </div>
    </div>
</div>
