// src/UI/Components/Backpack/backpack.component.ts
import {ICharacter, IGame, IGroupableItem, IInterfaceTexts, IItem} from 'storyScript/Interfaces/storyScript';
import {SharedMethodService} from '../../Services/SharedMethodService';
import {ServiceFactory} from 'storyScript/ServiceFactory.ts';
import {Component, inject, Input} from '@angular/core';
import {getTemplate} from '../../helpers';
import {ItemService} from "storyScript/Services/ItemService.ts";

@Component({
    selector: 'backpack',
    template: getTemplate('backpack', await import('./backpack.component.html?raw'))
})
export class BackpackComponent {
    @Input() character!: ICharacter;
    private _itemService: ItemService;
    private _sharedMethodService: SharedMethodService;

    constructor() {
        this._itemService = inject(ItemService);
        this._sharedMethodService = inject(SharedMethodService);
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this._sharedMethodService.useBackpack = true;
    }

    game: IGame;
    texts: IInterfaceTexts;
    joinItem: IGroupableItem<IItem>;

    hasDescription = (item: IItem): boolean => this._sharedMethodService.hasDescription(item);

    showDescription = (item: IItem, title: string): void => this._sharedMethodService.showDescription('item', item, title);

    getCombineClass = (item: IItem): string => this.game.combinations.getCombineClass(item);

    tryCombine = (item: IItem): boolean => this._sharedMethodService.tryCombine(item);

    showEquipment = (): boolean => this._sharedMethodService.showEquipment(this.character);

    getItemName = (item: IItem): string => this._itemService.getItemName(item);

    canEquip = (item: IItem): boolean => this._itemService.isEquippable(item);

    canDrop = (item: IItem): boolean => this._itemService.canDrop(item);

    equipItem = (item: IItem): boolean => this._itemService.equipItem(this.character, item);

    canUseItem = (item: IItem): boolean => this._sharedMethodService.canUseItem(this.character, item);

    useItem = (item: IItem): Promise<void> | void => this._itemService.useItem(this.character, item);

    canDropItems = (): boolean => this._sharedMethodService.useGround;

    dropItem = (item: IItem): void => this._itemService.dropItem(this.character, item);

    canGroupItem = (item: IGroupableItem<IItem>): boolean => this._itemService.canGroupItem(this.character, this.joinItem, item)

    groupItem = (item: IGroupableItem<IItem>): void => {
        if (this.joinItem && this._itemService.groupItem(this.character, this.joinItem, item)) {
            this.joinItem = null;
        } else {
            this.joinItem = item;
        }
    }
}
<div class="box-container" id="character-backpack">
    <div class="box-title" (click)="isCollapsed = !isCollapsed">{{ texts.backpack }}</div>
    <ul id="backpack-panel" [ngbCollapse]="isCollapsed" class="collapse navbar-collapse list-unstyled">
        @for (item of character.items; track item.id) {
            <li>
                <div (click)="tryCombine(item)" [ngClass]="getCombineClass(item)">
                    <span>{{ getItemName(item) }}</span>
                    <div id="backpack-button-row" class="inline" [ngClass]="getCombineClass()">
                        @if (canEquip(item) && showEquipment()) {
                            <button type="button" class="btn btn-info btn-sm" (click)="equipItem(item)">{{ texts.equip }}</button>
                        }
                        @if (hasDescription(item)) {
                            <button type="button" class="btn btn-info btn-sm" (click)="showDescription(item, getItemName(item))">{{ texts.view }}</button>
                        }
                        @if (canUseItem(item)) {
                            <button type="button" class="btn btn-info btn-sm" (click)="useItem(item)">{{ texts.use }}</button>
                        }
                        @if (canGroupItem(item)) {
                            <button type="button" class="btn btn-sm"
                                    [ngClass]="{ 'btn-primary': item === joinItem, 'btn-outline-secondary': joinItem && item !== joinItem, 'btn-info': !joinItem  }"
                                    (click)="groupItem(item)">{{ texts.groupItem }}
                            </button>
                        }
                        @if (item.members?.length > 0)
                        {
                            <button type="button" class="btn btn-info btn-sm" (click)="splitItemGroup(item)">{{ texts.splitItemGroup }}</button>
                        }
                        @if (canDropItems() && canDrop(item)) {
                            <button type="button" class="btn btn-info btn-sm" (click)="dropItem(item)">{{ texts.drop }}</button>
                        }
                    </div>
                </div>
            </li>
        }
    </ul>
</div>

// src/UI/Components/Party/Backpack.vue
<template>
  <div class="box-container" id="character-backpack">
    <collapsible :text="texts.backpack" :headerClass="'box-title'">
      <ul id="backpack-panel" class="list-unstyled">
        <li v-for="item of character.items">
          <div @click="tryCombine(game, item)" :class="game.combinations.getCombineClass(item)">
            <span>{{ getItemName(item) }}</span>
            <div id="backpack-button-row" class="inline">
              <button v-if="canEquip(item) && showEquipment(useEquipment, character)" type="button" class="btn btn-info btn-sm" @click="equipItem(item)">{{ texts.equip }}</button>
              <button v-if="hasDescription(item)" type="button" class="btn btn-info btn-sm" @click="showDescription(game, 'item', item, getItemName(item))">{{ texts.view }}</button>
              <button v-if="canUseItem(game, character, item)" type="button" class="btn btn-info btn-sm" @click="useItem(item)">{{ texts.use }}</button>
              <button v-if="canGroupItem(item as IGroupableItem<IItem>)" type="button" class="btn btn-sm"
                      :class="{ 'btn-primary': item === joinItem, 'btn-outline-secondary': joinItem && item !== joinItem, 'btn-info': !joinItem  }"
                      @click="groupItem(item as IGroupableItem<IItem>)">{{ texts.groupItem }}
              </button>
              <button v-if="(item as IGroupableItem<IItem>).members?.length > 0" type="button" class="btn btn-info btn-sm" @click="splitItemGroup(item as IGroupableItem<IItem>)">{{ texts.splitItemGroup }}</button>
              <button v-if="useGround && canDrop(item)" type="button" class="btn btn-info btn-sm" @click="dropItem(item)">{{ texts.drop }}</button>
            </div>
          </div>
        </li>
      </ul>
    </collapsible>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {IGroupableItem} from "storyScript/Interfaces/groupableItem.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {ref} from "vue";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {canUseItem, showDescription, showEquipment, tryCombine} from "ui/Helpers.ts";
import {hasDescription} from "storyScript/Services/sharedFunctions.ts";

const store = useStateStore();
const {game, useGround, useBackpack, useEquipment} = storeToRefs(store);
const {texts, itemService} = store.services;

const { character } = defineProps<{
  character?: ICharacter
}>();

const joinItem = ref<IGroupableItem<IItem>>(null);

useBackpack.value = true;

const getItemName = (item: IItem): string => itemService.getItemName(item);

const canEquip = (item: IItem): boolean => itemService.isEquippable(item, character);

const canDrop = (item: IItem): boolean => itemService.canDrop(item);

const equipItem = (item: IItem): boolean => itemService.equipItem(character, item);

const useItem = (item: IItem): Promise<void> | void => itemService.useItem(character, item);

const dropItem = (item: IItem): void => itemService.dropItem(character, item);

const canGroupItem = (item: IGroupableItem<IItem>): boolean => itemService.canGroupItem(character, joinItem.value, item)

const groupItem = (item: IGroupableItem<IItem>): void => {
  if (joinItem && itemService.groupItem(character, joinItem.value, item)) {
    joinItem.value = null;
  } else {
    joinItem.value = item;
  }
}

const splitItemGroup = (item: IGroupableItem<IItem>): void => itemService.splitItemGroup(character, item);

</script>
