// src/UI/Components/CharacterSheet/charactersheet.component.ts
import { IInterfaceTexts, IGame, ICharacter } from 'storyScript/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { CharacterService } from 'storyScript/Services/characterService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component, Input, inject } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'character-sheet',
    template: getTemplate('charactersheet', await import('./charactersheet.component.html'))
})
export class CharacterSheetComponent { 
    @Input() character!: ICharacter;

    constructor() {
        const characterService = inject(CharacterService);
        const sharedMethodService = inject(SharedMethodService);
        const objectFactory = inject(ObjectFactory);
        this.texts = objectFactory.GetTexts();
        this.displayCharacterAttributes = characterService.getSheetAttributes();
        sharedMethodService.useCharacterSheet = true;
    }

    texts: IInterfaceTexts;
    displayCharacterAttributes: string[];
}
@let party = game.party;
<div class="box-container" id="character-attributes">
    <div class="box-title" (click)="isCollapsed = !isCollapsed">{{ character.name || texts.characterSheet }}</div>
    <div class="character-info" [ngbCollapse]="isCollapsed" class="collapse navbar-collapse list-unstyled">
        <div class="portraitFrame">
            <img class="portrait" src="{{character.portraitFileName}}" />
        </div>
        <ul id="attributes-panel" class="list-unstyled">
            @for (attribute of  displayCharacterAttributes; track attribute)
            {
                <li>
                    {{ texts.titleCase(texts.format(attribute)) }} {{ character[attribute] }}
                </li>
            }
            <li>{{ texts.hitpoints }} 
                <div class="hitpoint-editor">
                    @if (!game.isDevelopment) 
                    {
                        <span>{{ character.currentHitpoints }}</span>
                    }
                    @if (game.isDevelopment) 
                    {
                        <input type="number" min="{{ 1 }}" max="{{ character.hitpoints }}" [(ngModel)]="character.currentHitpoints" (blur)="limitInput($event, character)">
                    }
                </div> 
                &nbsp;/ {{ character.hitpoints }}
            </li>
            @if (party.characters.length === 1 && party.currency !== undefined) 
            {
                <li>{{ texts.currency }} {{ party.currency }}</li>   
            }
        </ul>
        <div class="clearfix"></div>
    </div>
</div>

// src/UI/Components/Party/CharacterSheet.vue
<template>
  <div id="character-attributes" class="box-container">
    <collapsible :text="character.name || texts.characterSheet" :headerClass="'box-title'">
      <div class="character-info">
        <div v-if="character.portraitFileName" class="portraitFrame">
          <img :alt="character.name" class="portrait" :src="character.portraitFileName"/>
        </div>
        <ul id="attributes-panel" class="list-unstyled">
          <li v-for="attribute of displayCharacterAttributes">
            {{ texts.titleCase(attribute) }} {{ character[attribute] }}
          </li>
          <li>{{ texts.hitpoints }}
            <div class="hitpoint-editor">
              <span v-if="!isDevelopment">{{ character.currentHitpoints }}</span>
              <input v-else v-model="character.currentHitpoints" :max="character.hitpoints" :min="1" type="number"
                     @blur="limitInput($event, character)">
            </div>
            &nbsp;/ {{ character.hitpoints }}
          </li>
          <li v-if="party.characters.length === 1 && party.currency !== undefined">{{ texts.currency }}
            {{ party.currency }}
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
    </collapsible>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {ref} from "vue";
import {IParty} from "storyScript/Interfaces/party.ts";
import {isDevelopment} from "ui/Helpers.ts";

const store = useStateStore();
const {useCharacterSheet} = storeToRefs(store);
const {texts, characterService} = store.services;

const {character} = defineProps<{
  party: IParty,
  character?: ICharacter
}>();

useCharacterSheet.value = true;

const displayCharacterAttributes = ref<string[]>(characterService.getSheetAttributes());

const limitInput = (event: any, character: ICharacter): void => {
  if (character.currentHitpoints > character.hitpoints) {
    character.currentHitpoints = character.hitpoints;
  } else if (character.currentHitpoints <= 0) {
    character.currentHitpoints = 1;
  }
}

</script>
