// src/UI/Angular/src/Components/LevelUp/levelup.component.ts
import { IGame, IInterfaceTexts, CreateCharacters, ICharacter } from '../../../../../Engine/Interfaces/storyScript';
import { GameService } from '../../../../../Engine/Services/gameService';
import { CharacterService } from '../../../../../Engine/Services/characterService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './levelup.component.html';

@Component({
    selector: 'level-up',
    template: template,
})
export class LevelUpComponent {
    constructor(private _gameService: GameService, private _characterService: CharacterService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    sheet: CreateCharacters.ICreateCharacter;
    game: IGame;
    texts: IInterfaceTexts;

    distributionDone = (step: CreateCharacters.ICreateCharacterStep): boolean => this._characterService.distributionDone(this.sheet, step);

    levelUp = (): ICharacter => this._gameService.levelUp();
}
<div id="level-up" *ngIf="game.state === 'LevelUp'" class="container-fluid">
    <div class="col-12">
        <h2>{{ texts.levelUp }}</h2>
        <p>{{ texts.format(texts.levelUpDescription, [game.character.level]) }}</p>
        <buildcharacter sheet="game.createCharacterSheet"></buildcharacter>
        <button type="button" class="btn btn-primary" [disabled]="!distributionDone()" (click)="levelUp()" *ngIf="game.createCharacterSheet.currentStep >= game.createCharacterSheet.steps.length - 1">{{ texts.completeLevelUp }}</button>
    </div>
</div>

// src/UI/Components/Party/LevelUp.vue
<template>
  <div id="level-up" class="container-fluid">
    <div class="col-12">
      <h2>{{ texts.levelUp }}</h2>
      <p>{{ texts.format(texts.levelUpDescription, [character.level.toString()]) }}</p>
      <build-character :sheet="sheet"></build-character>
      <button v-if="sheet.currentStep >= sheet.steps.length - 1" :disabled="!distributionDone()" class="btn btn-primary"
              type="button" @click="levelUp()">{{ texts.completeLevelUp }}
      </button>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {ICreateCharacter} from "storyScript/Interfaces/createCharacter/createCharacter.ts";

const store = useStateStore();
const {texts, characterService} = store.services;

const {character, sheet} = defineProps<{
  character: ICharacter;
  sheet: ICreateCharacter;
}>();

const distributionDone = (): boolean => characterService.distributionDone(sheet, null);

const levelUp = (): ICharacter => characterService.levelUp(character);

</script>
