// src/UserInterface/Components/Party/Party.vue
<template>
  <div v-if="party.characters.length > 1" class="box-container">
    <div class="box-title">{{ party.name }}</div>
    <ul class="list-unstyled">
      <li>{{ texts.currency }} {{ party.currency }}</li>
    </ul>
  </div>
  <div v-for="character of party.characters" :class="{ 'is-active': (<any>character).isActive, 'unavailable': character.currentHitpoints <= 0 }" class="character-container"
       @click="store.setActiveCharacter(character)">
    <character-sheet :character="character" :party="party"></character-sheet>
    <equipment :character="character"></equipment>
    <backpack :character="character"></backpack>
  </div>
  <quests :quests="party.quests"></quests>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {IParty} from "storyScript/Interfaces/party.ts";

const store = useStateStore();
const {texts} = storeToRefs(store);

const {party} = defineProps<{
  party?: IParty
}>();

</script>

// src/UI/Components/Party/party.component.ts
import { ICharacter, IGame, IInterfaceTexts, IParty } from 'storyScript/Interfaces/storyScript';
import { ServiceFactory } from 'storyScript/ServiceFactory.ts';
import { Component, Input, inject } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'party',
    template: getTemplate('party', await import('./party.component.html'))
})
export class PartyComponent {
    @Input() party!: IParty;

    constructor() {
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }
    
    game: IGame;
    texts: IInterfaceTexts;

    setActive(character: ICharacter) {
        this.game.activeCharacter = character;
    }

}
<div>
    <div class="box-container" *ngIf="party.characters.length > 1">
        <div class="box-title">{{party.name}}</div>
        <ul class="list-unstyled">
            <li>{{ texts.currency }} {{ party.currency }}</li>
        </ul>
    </div>
    <div *ngFor="let character of game.party.characters" (click)="setActive(character)" [ngClass]="{ 'is-active': character.isActive }">
        <character-sheet [character]="character"></character-sheet>
        <equipment [character]="character"></equipment>
        <backpack [character]="character"></backpack>
    </div>
    <quests></quests>
</div>
