// src/UI/Components/Conversation/conversation.component.ts
import { IGame, IConversationNode, IConversationReply } from 'storyScript/Interfaces/storyScript';
import { ConversationService } from 'storyScript/Services/ConversationService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component } from '@angular/core';
import template from './conversation.component.html';

@Component({
    selector: 'conversation',
    template: template,
})
export class ConversationComponent {
    constructor(private _conversationService: ConversationService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
    }

    game: IGame;

    answer = (node: IConversationNode, reply: IConversationReply): void => this._conversationService.answer(node, reply);

    getLines = (nodeOrReply: IConversationNode | IConversationReply): string => this._conversationService.getLines(nodeOrReply);
}
@let activeNode = game.person?.conversation?.activeNode;
@if (game.playState === 'Conversation')
{
    <div id="conversation">
        @if (activeNode)
        {
            <div id="conversation-options">
                <div [innerHTML]="getLines(activeNode) | safe: 'html'"></div>
                @for (reply of activeNode.replies; track reply)
                {
                    @if (reply.available || reply.showWhenUnavailable)
                    {
                        <div [ngClass]="{ 'unavailable': !reply.available }">
                            <input type="radio" [disabled]="!reply.available" (click)="answer(activeNode, reply)" />
                            <span [innerHTML]="getLines(reply) | safe: 'html'"></span>
                        </div>
                    }
                }
            </div>
        }
        @if (!activeNode || !activeNode.replies.length)
        {
            <div>
                Your conversation has ended.
            </div>
        }
        <div id="conversation-history">
            <hr />
            <p id="conversation-history-title">Conversation history</p>
            <ul class="list-unstyled">
                @for (entry of game.person.conversation.conversationLog; track $index)
                {
                    <li>
                        <div class="conversation-lines" [innerHTML]="entry.lines | safe: 'html'"></div>
                        <div class="conversation-option" [innerHTML]="entry.reply | safe: 'html'"></div>
                    </li>
                }
            </ul>
        </div>
    </div>
}

// src/UI/Components/Encounter/Conversation.vue
<template>
  <modal-dialog :canClose="true"
                :closeButton="true"
                :openState="PlayState.Conversation"
                :title="game.person.conversation.title || texts.format(texts.talk, [game.person.name])">
    <div id="conversation">
      <div v-if="game.person.conversation.activeNode" id="conversation-options">
        <div v-html="getLines(game.person.conversation.activeNode)"></div>
        <div v-for="reply of game.person.conversation.activeNode.replies">
          <div v-if="reply.available || reply.showWhenUnavailable" :class="{ 'unavailable': !reply.available }">
            <input :disabled="!reply.available" type="radio" @click="answer(game.person.conversation.activeNode, reply)"/>
            <span v-html="getLines(reply)"></span>
          </div>
        </div>
      </div>

      <div v-if="!game.person.conversation.activeNode || !game.person.conversation.activeNode.replies.length">
        {{ texts.conversationEnded }}
      </div>

      <div id="conversation-history">
        <hr/>
        <p id="conversation-history-title">Conversation history</p>
        <ul class="list-unstyled">
          <li v-for="entry of game.person.conversation.conversationLog">
            <div class="conversation-lines" v-html="entry.lines"></div>
            <div class="conversation-option" v-html="entry.reply"></div>
          </li>
        </ul>
      </div>
    </div>
  </modal-dialog>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {PlayState} from "storyScript/Interfaces/enumerations/playState.ts";
import {IConversationNode} from "storyScript/Interfaces/conversations/conversationNode.ts";
import {IConversationReply} from "storyScript/Interfaces/conversations/conversationReply.ts";
import {IPerson} from "storyScript/Interfaces/person.ts";
import {storeToRefs} from "pinia";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, conversationService} = store.services;

const answer = (node: IConversationNode, reply: IConversationReply): void => conversationService.answer(node, reply);

const getLines = (nodeOrReply: IConversationNode | IConversationReply): string => nodeOrReply?.lines || null;

</script>
