// src/UI/Angular/src/Components/Enemy/enemy.component.ts
import { IGame, IInterfaceTexts, IItem, IEnemy } from '../../../../../Engine/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './enemy.component.html';

@Component({
    selector: 'enemy',
    template: template,
})
export class EnemyComponent {
    constructor(private _sharedMethodService: SharedMethodService, private _objectFacory: ObjectFactory) {
        this.game = _objectFacory.GetGame();
        this.texts = _objectFacory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    getCombineClass = (item: IItem): string => this.game.combinations.getCombineClass(item);

    tryCombine = (enemy: IEnemy): boolean => this._sharedMethodService.tryCombine(this.game, enemy);

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent(this.game);

    showDescription = (item: any, title: string): void => this._sharedMethodService.showDescription('enemies', item, title);  

    startCombat = (): void => this._sharedMethodService.startCombat(this.game);
}
<div class="box-container" id="enemies" *ngIf="game.currentLocation.activeEnemies && game.currentLocation.activeEnemies.length">
    <div class="box-title">{{ texts.encounters }}</div>
    <p>{{ texts.enemiesToFight }}</p>
    <ul class="list-unstyled">
        <li *ngFor="let enemy of game.currentLocation.activeEnemies" (click)="tryCombine(enemy)" [ngClass]="getCombineClass(enemy)">
            <span>{{ enemy.name }}</span>
            <div class="inline" [ngClass]="getCombineClass()">
                <button type="button" class="btn btn-info btn-sm" *ngIf="hasDescription('enemies', enemy)" (click)="showDescription(enemy, enemy.name)">{{ texts.view }}</button>
            </div>
        </li>
    </ul>
    <button type="button" class="btn btn-danger" id="start-combat" (click)="startCombat()">{{ texts.startCombat }}</button>
</div>

// src/UI/Components/Encounter/Enemy.vue
<template>
  <div v-if="enemiesPresent(game)" class="box-container">
    <div class="box-title">{{ texts.encounters }}</div>
    <p>{{ texts.enemiesToFight }}</p>
    <ul class="list-unstyled enemy-list">
      <li v-for="enemy of game.currentLocation.activeEnemies" :class="combinations.getCombineClass(enemy)"
          @click="tryCombine(game, enemy)">
        <span class="enemy-name">{{ enemy.name }}</span>
        <div :class="combinations.getCombineClass(enemy)" class="inline">
          <button v-if="hasDescription(enemy)" class="btn btn-info btn-sm" type="button"
                  @click="showDescription(game, 'enemy', enemy, enemy.name)">{{ texts.view }}
          </button>
        </div>
        <img v-if="enemy.picture" :alt="enemy.name" :src="enemy.picture" class="enemy-picture"/>
      </li>
    </ul>
    <button id="start-combat" class="btn btn-danger" type="button" @click="store.startCombat(game.currentLocation)">
      {{ texts.startCombat }}
    </button>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {IEnemy} from "storyScript/Interfaces/enemy.ts";
import {enemiesPresent, showDescription, tryCombine} from "ui/Helpers.ts";
import {storeToRefs} from "pinia";
import {IGameCombinations} from "storyScript/Interfaces/combinations/gameCombinations.ts";
import {hasDescription} from "storyScript/Services/sharedFunctions.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts} = store.services;

const {enemies, combinations} = defineProps<{
  enemies: IEnemy[],
  combinations?: IGameCombinations
}>();

</script>
