// src/UI/Components/Exploration/exploration.component.ts
import { IGame, IInterfaceTexts, IPerson, ITrade, IAction, IDestination, IBarrier, IBarrierAction, ActionStatus } from 'storyScript/Interfaces/storyScript';
import { isEmpty } from 'storyScript/utilities';
import { GameService } from 'storyScript/Services/gameService';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component } from '@angular/core';
import template from './exploration.component.html';

@Component({
    selector: 'exploration',
    template: template,
})
export class ExplorationComponent {
    constructor(private _gameService: GameService, private _sharedMethodService: SharedMethodService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    changeLocation = (location: string): void => this.game.changeLocation(location, true);

    actionsPresent = (): boolean => this.game.currentLocation && !this.enemiesPresent() && !isEmpty(this.game.currentLocation.actions);

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent(this.game);

    getButtonClass = (action: IAction): string => this._sharedMethodService.getButtonClass(action);

    getCombineClass = (barrier: IBarrier): string => this.game.combinations.getCombineClass(barrier);

    disableActionButton = (action: IAction): boolean => typeof action.status === 'function' ? (<any>action).status(this.game) == ActionStatus.Disabled : action.status == undefined ? false : (<any>action).status == ActionStatus.Disabled;

    hideActionButton = (action: IAction): boolean => typeof action.status === 'function' ? (<any>action).status(this.game) == ActionStatus.Unavailable : action.status == undefined ? false : (<any>action).status == ActionStatus.Unavailable;

    executeAction = (action: IAction): void => this._sharedMethodService.executeAction(this.game, action, this);

    trade = (game: IGame, trade: IPerson | ITrade): boolean => this._sharedMethodService.trade(this.game, trade);

    executeBarrierAction = (barrier: IBarrier, action: IBarrierAction, destination: IDestination): void => {
        if (this.game.combinations.tryCombine(barrier))
        {
            return;
        }
        else if (this.game.combinations.activeCombination) {
            return;
        }

        this._gameService.executeBarrierAction(barrier, action, destination);
    }
}
<div id="exploration">
    @if (actionsPresent())
    {
        <div class="box-container" id="exploration-actions">
            <div class="box-title">{{ texts.actions }}</div>
            @if (!confirmAction)
            {
                <ul class="list-unstyled">
                    @for (action of game.currentLocation.activeActions; track action)
                    {
                        @if (!hideActionButton(action))
                        {
                            <li class="inline">
                                <button type="button" class="btn" [ngClass]="getButtonClass(action)" (click)="executeAction(action)" [disabled]="disableActionButton(action)">{{ action[1].text }}</button>
                            </li>
                        }
                    }
                </ul>
            }
            @if (confirmAction)
            {
                <div>
                    <p [innerHTML]="confirmAction[1].confirmationText | safe: 'html'"></p>
                    <ul class="list-unstyled">
                        <li class="inline">
                            <button type="button" class="btn btn-primary" (click)="cancelAction()">{{ texts.cancelAction }}</button>
                            <button type="button" class="btn btn-warning" (click)="executeAction(confirmAction)">{{ texts.confirmAction }}</button>
                        </li>
                    </ul>
                </div>
            }
        </div>
    }
    @if (!enemiesPresent())
    {
        <div class="box-container" id="exploration-destinations">
            <div class="box-title">{{ texts.destinations }}</div>
            <ul class="list-unstyled">
                @for (destination of game.currentLocation.activeDestinations; track destination.target)
                {
                    <li class="inline">
                        @for (barrier of destination.barriers; track barrier)
                        {
                            <div class="barrier">
                                @let barrierEntry = barrier[1];
                                @if (!barrierEntry.actions?.length)
                                {
                                    <button class="btn btn-outline-primary">{{ barrierEntry.name }}</button>
                                }
                                @if (barrierEntry.actions?.length)
                                {
                                    <div ngbDropdown class="d-inline-block" class="action-select">
                                        <button class="btn btn-outline-primary" id="barrierdropdown" ngbDropdownToggle>{{ barrierEntry.name }}</button>
                                        <div ngbDropdownMenu aria-labelledby="barrierdropdown">
                                            @for (action of barrier[1].actions; track action)
                                            {
                                                <button ngbDropdownItem (click)="executeBarrierAction(barrier, action, destination)">{{ action[1].text }}</button>
                                            }
                                        </div>
                                    </div>
                                }
                            </div>
                        }
                        <button type="button" class="btn btn-info" [ngClass]="destination.style" (click)="changeLocation(destination.target)" [disabled]="!destination.target || destination.barriers?.length > 0">
                            @if (isPreviousLocation(destination))
                            {
                                <span class="back-label">{{ texts.back }}</span>
                            }
                            {{ destination.name }}
                        </button>
                    </li>
                }
            </ul>
        </div>
    }
</div>

// src/UserInterface/Components/Exploration/Exploration.vue
<template>
  <div id="exploration">
    <div v-if="actionsPresent()" class="box-container" id="exploration-actions">
      <div class="box-title">{{ texts.actions }}</div>
      <ul v-if="!confirmAction" class="list-unstyled">
        <li v-for="action of location.activeActions.filter(a => !checkStatus(a, ActionStatus.Unavailable))" class="inline">
          <button type="button" class="btn" :class="getButtonClass(action)" @click="execute(action)" :disabled="disableActionButton(action)">{{ action[1].text }}</button>
        </li>
      </ul>
      <div v-else>
        <p v-html="confirmAction[1].confirmationText"></p>
        <ul class="list-unstyled">
          <li class="inline">
            <button type="button" class="btn btn-primary" @click="cancelAction()">{{ texts.cancelAction }}</button>
            <button type="button" class="btn btn-warning" @click="execute(confirmAction)">{{ texts.confirmAction }}</button>
          </li>
        </ul>
      </div>
    </div>
    <div v-if="!enemiesPresent(game)" class="box-container" id="exploration-destinations">
      <div class="box-title">{{ texts.destinations }}</div>
      <ul class="list-unstyled">
        <li v-for="destination of location.activeDestinations" :class="`inline ${destination.visited ? '' : 'not-'}visited`">
          <div v-for="barrier of destination.barriers?.map(b => b[1])" class="barrier">
            <button v-if="!barrier.actions?.length" class="btn btn-outline-primary">{{ barrier.name }}</button>
<!--            <div v-else ngbDropdown class="d-inline-block" class="action-select">-->
<!--              <button class="btn btn-outline-primary" id="barrierdropdown" ngbDropdownToggle>{{ barrierEntry.name }}</button>-->
<!--              <div ngbDropdownMenu aria-labelledby="barrierdropdown">-->
<!--                @for (action of barrier[1].actions; track action)-->
<!--                {-->
<!--                <button ngbDropdownItem (click)="executeBarrierAction(barrier, action, destination)">{{ action[1].text }}</button>-->
<!--                }-->
<!--              </div>-->
<!--            </div>-->
          </div>
          <button type="button" class="btn btn-info" :class="destination.style" @click="changeLocation(<string>destination.target)" :disabled="!destination.target || destination.barriers?.length > 0">
            <span v-if="(<any>destination).isPreviousLocation" class="back-label">{{ texts.back }}</span>
            {{ destination.name }}
          </button>
        </li>
      </ul>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {enemiesPresent, getButtonClass, executeAction} from "vue/Helpers.ts";
import {isEmpty} from "storyScript/utilityFunctions.ts";
import {IAction} from "storyScript/Interfaces/action.ts";
import {ref} from "vue";
import {ActionStatus} from "storyScript/Interfaces/enumerations/actionStatus.ts";
import {ICompiledLocation} from "storyScript/Interfaces/compiledLocation.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, dataService} = store.services;

const confirmAction = ref<IAction>(null);

const { location } = defineProps<{
  location?: ICompiledLocation
}>();

const checkStatus = (action: IAction, status: ActionStatus) => 
    typeof action[1].status === 'function' 
        ? (<any>action[1]).status(game) == status 
        : action[1].status == undefined ? false : action[1].status == status;

const actionsPresent = () => location && !enemiesPresent(game.value) && !isEmpty(location.actions);

const disableActionButton = (a) => checkStatus(a, ActionStatus.Disabled);

const cancelAction = () => confirmAction.value = undefined;

const execute = (action: IAction): void => {
  if (action[1].confirmationText && !confirmAction) {
    confirmAction.value = action;
    return;
  }

  confirmAction.value = undefined;
  executeAction(game.value, action, this, () => dataService.saveGame(game.value));
}

const changeLocation = (location: string) => game.value.changeLocation(location, true);

</script>
