// src/UI/src/Components/Exploration/exploration.component.ts
import { IGame, IInterfaceTexts, IPerson, ITrade, IAction, Enumerations, IDestination, IBarrier, IBarrierAction } from '../../../../Engine/Interfaces/storyScript';
import { isEmpty } from '../../../../Engine/utilities';
import { GameService } from '../../../../Engine/Services/gameService';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from '../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './exploration.component.html';

@Component({
    selector: 'exploration',
    template: template,
})
export class ExplorationComponent {
    constructor(private _gameService: GameService, private _sharedMethodService: SharedMethodService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    trade = (game, trade: IPerson | ITrade): boolean => this._sharedMethodService.trade(this.game, trade);

    changeLocation = (location: string): void => this.game.changeLocation(location, true);

    actionsPresent = (): boolean => this.game.currentLocation && !this.enemiesPresent() && !isEmpty(this.game.currentLocation.actions);

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent(this.game);

    getButtonClass = (action: IAction): string => this._sharedMethodService.getButtonClass(action);

    getCombineClass = (barrier: IBarrier): string => this.game.combinations.getCombineClass(barrier);

    disableActionButton = (action: IAction): boolean => typeof action.status === 'function' ? (<any>action).status(this.game) == Enumerations.ActionStatus.Disabled : action.status == undefined ? false : (<any>action).status == Enumerations.ActionStatus.Disabled;

    hideActionButton = (action: IAction): boolean => typeof action.status === 'function' ? (<any>action).status(this.game) == Enumerations.ActionStatus.Unavailable : action.status == undefined ? false : (<any>action).status == Enumerations.ActionStatus.Unavailable;

    executeAction = (action: IAction): void => this._sharedMethodService.executeAction(this.game, action, this);

    executeBarrierAction = (barrier: IBarrier, action: IBarrierAction, destination: IDestination): void => {
        if (this.game.combinations.tryCombine(barrier))
        {
            return;
        }
        else if (this.game.combinations.activeCombination) {
            return;
        }

        this._gameService.executeBarrierAction(barrier, action, destination);
    }
}
<div id="exploration">
    <div class="box-container" id="exploration-actions" *ngIf="actionsPresent()">
        <div class="box-title">{{ texts.actions }}</div>
        <ul class="list-unstyled">
            <li class="inline" *ngFor="let action of game.currentLocation.actions">
                <button type="button" class="btn" [ngClass]="getButtonClass(action)" (click)="executeAction(action)" [disabled]="disableActionButton(action)" *ngIf="!hideActionButton(action)">{{ action.text }}</button>
            </li>
        </ul>
    </div>
    <div class="box-container" id="exploration-destinations" *ngIf="!enemiesPresent()">
        <div class="box-title">{{ texts.destinations }}</div>
        <ul class="list-unstyled">
            <li class="inline" *ngFor="let destination of game.currentLocation.activeDestinations">
                <div class="barrier" *ngIf="destination.barrier">
                    <button type="button" class="btn btn-info" (click)="executeBarrierAction(destination.barrier, destination)" [ngClass]="getCombineClass(destination.barrier)">{{ destination.barrier.name }}</button>
                    <select [(ngModel)]="destination.barrier.selectedAction" class="action-select" *ngIf="destination.barrier.actions.length > 0">
                        <option *ngFor="let action of destination.barrier.actions" [ngValue]="action">{{ action.text }}</option>
                    </select>
                </div>
                <button type="button" class="btn btn-info" [ngClass]="destination.style" (click)="changeLocation(destination.target)" [disabled]="!destination.target || destination.barrier || game.currentLocation.navigationDisabled"><span class="back-label" *ngIf="destination.isPreviousLocation">{{ texts.back }}</span> {{ destination.name }}</button>
            </li>
        </ul>
    </div>
</div>

// src/UserInterface/Components/Exploration/Exploration.vue
<template>
  <div id="exploration">
    <div v-if="actionsPresent()" class="box-container" id="exploration-actions">
      <div class="box-title">{{ texts.actions }}</div>
      <ul v-if="!confirmAction" class="list-unstyled">
        <li v-for="action of location.activeActions.filter(a => !checkStatus(a, ActionStatus.Unavailable))" class="inline">
          <button type="button" class="btn" :class="getButtonClass(action)" @click="execute(action)" :disabled="disableActionButton(action)">{{ action[1].text }}</button>
        </li>
      </ul>
      <div v-else>
        <p v-html="confirmAction[1].confirmationText"></p>
        <ul class="list-unstyled">
          <li class="inline">
            <button type="button" class="btn btn-primary" @click="cancelAction()">{{ texts.cancelAction }}</button>
            <button type="button" class="btn btn-warning" @click="execute(confirmAction)">{{ texts.confirmAction }}</button>
          </li>
        </ul>
      </div>
    </div>
    <div v-if="!enemiesPresent(game)" class="box-container" id="exploration-destinations">
      <div class="box-title">{{ texts.destinations }}</div>
      <ul class="list-unstyled">
        <li v-for="destination of location.activeDestinations" :class="`inline ${destination.visited ? '' : 'not-'}visited`">
          <div v-for="barrier of destination.barriers" class="barrier">
            <button v-if="!barrier[1].actions?.length" class="btn btn-outline-primary">{{ barrier[1].name  }}</button>
            <div v-else class="dropdown">
              <button class="btn btn-outline-primary dropdown-toggle" type="button" @click="dropDownExpanded = !dropDownExpanded" :aria-expanded="dropDownExpanded">
                {{ barrier[1].name }}
              </button>
              <ul class="dropdown-menu action-select" :class="dropDownMenuActive" v-if="dropDownExpanded">
                <li v-for="action of barrier[1].actions"><a class="dropdown-item" href="#" @click="executeBarrierAction(barrier, action, destination)">{{ action[1].text }}</a></li>
              </ul>
            </div>
          </div>
          <button type="button" class="btn btn-info" :class="destination.style" @click="changeLocation(<string>destination.target)" :disabled="!destination.target || destination.barriers?.length > 0">
            <span v-if="(<any>destination).isPreviousLocation" class="back-label">{{ texts.back }}</span>
            {{ destination.name }}
          </button>
        </li>
      </ul>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {enemiesPresent, getButtonClass, executeAction} from "vue/Helpers.ts";
import {isEmpty} from "storyScript/utilityFunctions.ts";
import {IAction} from "storyScript/Interfaces/action.ts";
import {computed, ref} from "vue";
import {ActionStatus} from "storyScript/Interfaces/enumerations/actionStatus.ts";
import {ICompiledLocation} from "storyScript/Interfaces/compiledLocation.ts";
import {IBarrier} from "storyScript/Interfaces/barrier.ts";
import {IBarrierAction} from "storyScript/Interfaces/barrierAction.ts";
import {IDestination} from "storyScript/Interfaces/destination.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, dataService} = store.services;

const dropDownExpanded = ref(false);
const confirmAction = ref<IAction>(null);

const dropDownMenuActive = computed(() => dropDownExpanded.value ? 'dropdown-menu-active' : '');

const { location } = defineProps<{
  location?: ICompiledLocation
}>();

const checkStatus = (action: IAction, status: ActionStatus) => 
    typeof action[1].status === 'function' 
        ? (<any>action[1]).status(game) == status 
        : action[1].status == undefined ? false : action[1].status == status;

const actionsPresent = () => location && !enemiesPresent(game.value) && !isEmpty(location.actions);

const disableActionButton = (a) => checkStatus(a, ActionStatus.Disabled);

const cancelAction = () => confirmAction.value = undefined;

const executeBarrierAction = (barrier: [string, IBarrier], action: [string, IBarrierAction], destination: IDestination): void => {
  if (game.value.combinations.tryCombine(barrier[1]).success || game.value.combinations.activeCombination) {
    return;
  }

  action[1].execute(game.value, barrier, destination);
  barrier[1].actions.delete(barrier[1].actions.find(([k, _]) => k === action[0]));
  dataService.saveGame(game.value);
}

const execute = (action: IAction): void => {
  if (action[1].confirmationText && !confirmAction) {
    confirmAction.value = action;
    return;
  }

  confirmAction.value = undefined;
  executeAction(game.value, action, this, () => dataService.saveGame(game.value));
}

const changeLocation = (location: string) => game.value.changeLocation(location, true);

</script>
