// src/UI/Components/Encounter/Enemy.vue
<template>
  <div v-if="enemiesPresent(game)" class="box-container">
    <div class="box-title">{{ texts.encounters }}</div>
    <p>{{ texts.enemiesToFight }}</p>
    <ul class="list-unstyled enemy-list">
      <li v-for="enemy of game.currentLocation.activeEnemies" :class="combinations.getCombineClass(enemy)"
          @click="tryCombine(game, enemy)">
        <span class="enemy-name">{{ enemy.name }}</span>
        <div :class="combinations.getCombineClass(enemy)" class="inline">
          <button v-if="hasDescription(enemy)" class="btn btn-info btn-sm" type="button"
                  @click="showDescription(game, 'enemy', enemy, enemy.name)">{{ texts.view }}
          </button>
        </div>
        <img v-if="enemy.picture" :alt="enemy.name" :src="enemy.picture" class="enemy-picture"/>
      </li>
    </ul>
    <button id="start-combat" class="btn btn-danger" type="button" @click="store.startCombat(game.currentLocation)">
      {{ texts.startCombat }}
    </button>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {IEnemy} from "storyScript/Interfaces/enemy.ts";
import {enemiesPresent, showDescription, tryCombine} from "ui/Helpers.ts";
import {storeToRefs} from "pinia";
import {IGameCombinations} from "storyScript/Interfaces/combinations/gameCombinations.ts";
import {hasDescription} from "storyScript/Services/sharedFunctions.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts} = store.services;

const {enemies, combinations} = defineProps<{
  enemies: IEnemy[],
  combinations?: IGameCombinations
}>();

</script>

// src/UI/Components/Enemy/enemy.component.ts
import { IGame, IInterfaceTexts, IItem, IEnemy } from 'storyScript/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'enemy',
    template: getTemplate('enemy', require('./enemy.component.html'))
})
export class EnemyComponent {
    constructor(private _sharedMethodService: SharedMethodService, objectFacory: ObjectFactory) {
        this.game = objectFacory.GetGame();
        this.texts = objectFacory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    getCombineClass = (item: IItem): string => this.game.combinations.getCombineClass(item);

    tryCombine = (enemy: IEnemy): boolean => this._sharedMethodService.tryCombine(this.game, enemy);

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent(this.game);

    hasDescription = (enemy: IEnemy): boolean => this._sharedMethodService.hasDescription(enemy);

    showDescription = (enemy: IEnemy, title: string): void => this._sharedMethodService.showDescription(this.game, 'enemies', enemy, title);  

    startCombat = (): void => this._sharedMethodService.startCombat(this.game);
}
@if (enemiesPresent())
{
    <div class="box-container">
        <div class="box-title">{{ texts.encounters }}</div>
        <p>{{ texts.enemiesToFight }}</p>
        <ul class="list-unstyled enemy-list">
            @for (enemy of game.currentLocation.activeEnemies; track enemy)
            {
                <li (click)="tryCombine(enemy)" [ngClass]="getCombineClass(enemy)">
                    <span class="enemy-name">{{ enemy.name }}</span>
                    <div class="inline" [ngClass]="getCombineClass()">
                        @if (hasDescription(enemy))
                        {
                            <button type="button" class="btn btn-info btn-sm" (click)="showDescription(enemy, enemy.name)">{{ texts.view }}</button>
                        }
                    </div>
                    @if (enemy.picture)
                    {
                        <img class="enemy-picture" src="{{ enemy.picture }}" alt="{{ enemy.name }}" />
                    }
                </li>
            }
        </ul>
        <button type="button" class="btn btn-danger" id="start-combat" (click)="startCombat()">{{ texts.startCombat }}</button>
    </div>
}
