// src/UI/src/Components/Intro/intro.component.ts

import { IGame, IInterfaceTexts } from '../../../../Engine/Interfaces/storyScript';
import { GameService } from '../../../../Engine/Services/gameService';
import { ObjectFactory } from '../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './intro.component.html';

@Component({
    selector: 'intro',
    template: template,
})
export class IntroComponent {
    constructor(private _gameService: GameService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    endIntro = (): void => this._gameService.restart(true);
}

// src/UI/Components/GameState/Intro.vue
<template>
  <div v-if="game.state === GameState.Intro" id="intro" class="box-container">
    <h2>Game introduction</h2>
    <p>Please copy the IntroComponent.html file to your game and add your introduction here.</p>
    <button class="btn btn-primary" type="button" @click="endIntro()">{{ texts.skipIntro }}</button>
  </div>
</template>
<script lang="ts" setup>

import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {GameState} from "storyScript/Interfaces/storyScript.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, gameService} = store.services;

const endIntro = (): void => gameService.restart(true);

</script>
