// src/UI/src/Components/Victory/victory.component.ts
import { IGame, IInterfaceTexts } from '../../../../Engine/Interfaces/storyScript';
import { GameService } from '../../../../Engine/Services/gameService';
import { ObjectFactory } from '../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './victory.component.html';

@Component({
    selector: 'victory',
    template: template,
})
export class VictoryComponent {
    constructor(private _gameService: GameService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    restart = (): void => this._gameService.restart();
}
<div *ngIf="game.state === 'Victory'" class="container-fluid">
    <div class="col-12">
        <h1>{{ texts.youWon }}</h1>
        <div><span>{{ texts.congratulations }}</span></div>
        <div><span>{{ texts.finalScore }}{{ game.character.score }}</span></div>
        <button type="button" class="btn btn-primary" (click)="restart()">{{ texts.playAgain }}</button>
        <highscores></highscores>
    </div>
</div>

// src/UI/Components/GameState/Victory.vue
<template>
  <div v-if="game.state === GameState.Victory" id="victory" class="container-fluid">
    <div class="col-12">
      <h1>{{ texts.youWon }}</h1>
      <div><span>{{ texts.congratulations }}</span></div>
      <div><span>{{ texts.finalScore }}{{ game.party.score }}</span></div>
      <button class="btn btn-primary" type="button" @click="gameService.restart()">{{ texts.playAgain }}</button>
      <high-scores v-if="game.party.score > 0" :scores="game.highScores"></high-scores>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "ui/StateStore.ts";
import {storeToRefs} from "pinia";
import {GameState} from "storyScript/Interfaces/storyScript.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, gameService} = store.services;

</script>
