// src/UserInterface/Components/Party/BuildCharacter.vue
<template>
  <div id="create-character" class="container-fluid">
    <div v-for="(step, index) of sheet.steps" :hidden="sheet.currentStep !== index">
      <div v-if="step.description" class="step-description" v-html="step.description"></div>
      <div v-for="question of step.questions" class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text">{{ question.question }}</label>
        </div>
        <select class="custom-select" v-model="question.selectedEntry" @change="sheet.nextStep(sheet, false)">
          <option v-for="entry of question.entries" :value="entry" >{{ entry.text }}</option>
        </select>
      </div>

      <div v-for="attribute of step.attributes">
        <div v-if="attribute.entries.length > 1">
          <span class="attribute-header">{{ attribute.question }}</span>
        </div>
        <div v-for="entry of attribute.entries" class="input-group mb-3">
          <div class="input-group-prepend">
            <label v-if="attribute.entries.length !== 1" class="input-group-text">{{ texts.titleCase(entry.attribute) }}</label>
            <label v-if="attribute.entries.length === 1" class="input-group-text">{{ attribute.question }}</label>
          </div>
          <input v-if="!entry.min && !entry.max" class="form-control" type="text" v-model="entry.value" />
          <input v-if="entry.min || entry.max" class="form-control" type="number" min="{{ entry.min }}" max="{{ entry.max }}" v-model="entry.value" @blur="limitInput($event, attribute, entry)" />
        </div>
      </div>
      
      <button v-if="sheet.currentStep < sheet.steps.length - 1 && !sheet.steps[sheet.currentStep].finish" type="button" class="btn btn-primary" :disabled="!distributionDone(step)" @click="sheet.nextStep(sheet)">{{ texts.nextQuestion }}</button>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {ICreateCharacterAttribute} from "storyScript/Interfaces/createCharacter/createCharacterAttribute.ts";
import {ICreateCharacterAttributeEntry} from "storyScript/Interfaces/createCharacter/createCharacterAttributeEntry.ts";
import {ICreateCharacterStep} from "storyScript/Interfaces/createCharacter/createCharacterStep.ts";
import type {ICreateCharacter} from "storyScript/Interfaces/createCharacter/createCharacter.ts";

const store = useStateStore();
const {texts, characterService} = store.services;

const {sheet} = defineProps<{
  sheet?: ICreateCharacter
}>();

const limitInput = (event: any, attribute: ICreateCharacterAttribute, entry: ICreateCharacterAttributeEntry): void => {
  const value = parseInt(event.target.value);
  characterService.limitSheetInput(value, attribute, entry);
}

const distributionDone = (step: ICreateCharacterStep): boolean => characterService.distributionDone(sheet, step);
</script>

// src/UI/Components/BuildCharacter/buildcharacter.component.ts
import { IInterfaceTexts, ICreateCharacter, ICreateCharacterStep, ICreateCharacterAttribute, ICreateCharacterAttributeEntry } from 'storyScript/Interfaces/storyScript';
import { CharacterService } from 'storyScript/Services/characterService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component, Input } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'build-character',
    template: getTemplate('buildcharacter', require('./buildcharacter.component.html'))
})
export class BuildCharacterComponent {
    @Input() sheet: ICreateCharacter;
    
    constructor(private _characterService: CharacterService, objectFactory: ObjectFactory) {
        this.texts = objectFactory.GetTexts();
    }

    texts: IInterfaceTexts;

    limitInput = (event: any, attribute: ICreateCharacterAttribute, entry: ICreateCharacterAttributeEntry): void => {
        var value = parseInt((<any>event).target.value);
        this._characterService.limitSheetInput(value, attribute, entry);
    }

    distributionDone = (step: ICreateCharacterStep): boolean => this._characterService.distributionDone(this.sheet, step);
}
<div id="create-character" class="container-fluid">
    @for (step of sheet.steps; track $index)
    {
        <div [hidden]="sheet.currentStep !== $index">
            @if (step.description) {
                <div class="step-description" [innerHTML]="step.description | safe: 'html'"></div>
            }
            @for (question of step.questions; track question.question)
            {
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text">{{ question.question }}</label>
                    </div>
                    <select class="custom-select" [(ngModel)]="question.selectedEntry" (ngModelChange)="sheet.nextStep(sheet, false)">
                        @for (entry of question.entries; track entry.text)
                        {
                            <option [ngValue]="entry" >{{ entry.text }}</option>
                        }
                    </select>
                </div>
            }
            @for (attribute of step.attributes; track attribute.question)
            {
                <div>
                    @if (attribute.entries.length > 1)
                    {
                        <div>
                            <span class="attribute-header">{{ attribute.question }}</span>
                        </div>
                    }
                    @for (entry of attribute.entries; track entry.attribute)
                    {
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                @if (attribute.entries.length !== 1) 
                                {
                                    <label class="input-group-text">{{ texts.titleCase(entry.attribute) }}</label>
                                }
                                @if (attribute.entries.length === 1) {
                                    <label class="input-group-text">{{ attribute.question }}</label>
                                }
                            </div>
                            @if (!entry.min && !entry.max) 
                            {
                                <input class="form-control" type="text" [(ngModel)]="entry.value" />
                            }
                            @if (entry.min || entry.max)
                            {
                                <input class="form-control" type="number" min="{{ entry.min }}" max="{{ entry.max }}" [(ngModel)]="entry.value" (blur)="limitInput($event, attribute, entry)" />
                            }
                        </div>
                    }
                </div>
            }
            @if (sheet.currentStep < sheet.steps.length - 1 && !sheet.steps[sheet.currentStep].finish)
            {
                <button type="button" class="btn btn-primary" [disabled]="!distributionDone(step)" (click)="sheet.nextStep(sheet)">{{ texts.nextQuestion }}</button>
            }
        </div>
    }
</div>
