// src/UI/Components/Combat/combat.component.ts
import {
    IAction,
    ICharacter,
    ICombatTurn,
    IEnemy,
    IGame,
    IInterfaceTexts,
    IItem,
    TargetType
} from 'storyScript/Interfaces/storyScript';
import {SharedMethodService} from '../../Services/SharedMethodService';
import {ServiceFactory} from 'storyScript/ServiceFactory.ts';
import {Component, inject} from '@angular/core';
import {getTemplate} from '../../helpers';
import {CombatService} from "storyScript/Services/CombatService.ts";
import {CharacterService} from "storyScript/Services/CharacterService.ts";

@Component({
    selector: 'combat',
    template: getTemplate('combat', await import('./combat.component.html?raw'))
})
export class CombatComponent {
    private _characterService: CharacterService;
    private _combatService: CombatService;
    private _sharedMethodService: SharedMethodService;

    constructor() {
        this._characterService = inject(CharacterService);
        this._combatService = inject(CombatService);
        this._sharedMethodService = inject(SharedMethodService);
        const objectFactory = inject(ServiceFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this.multiCharacter = this.game.party.characters.length > 1;
        this.enemyRows = this.split(this.game.combat?.enemies, 3);
        this.characterRows = this.split(this.game.combat, 3);
    }

    game: IGame;
    texts: IInterfaceTexts;
    actionsEnabled: boolean = true;
    multiCharacter: boolean;
    enemyRows: IEnemy[];
    characterRows: ICharacter[];

    enemiesPresent = (): boolean => this._sharedMethodService.enemiesPresent();

    getButtonClass = (action: [string, IAction]): string => this._sharedMethodService.getButtonClass(action);

    executeAction = (action: [string, IAction]): void => this._sharedMethodService.executeAction(action, this);

    itemChange = (item: IItem, turn: ICombatTurn) => {
        const targets = turn.targetsAvailable.filter(t => {
            const type = (<any>t).type === 'enemy' ? TargetType.Enemy : TargetType.Ally;
            return item.targetType === type;
        });

        turn.target = targets[0];
    }

    filteredTargets = (turn: ICombatTurn): IEnemy[] | ICharacter[] => turn.targetsAvailable.filter(t => {
        const type = (<any>t).type === 'enemy' ? TargetType.Enemy : TargetType.Ally;
        return turn.item.targetType === type;
    });

    fight = (): void => {
        this.actionsEnabled = false;

        Promise.resolve(this._combatService.fight(this.game.combat)).then(() => {
            this.actionsEnabled = true;
            this.characterRows = this.split(this.game.combat, 3);
        });
    }

    itemSelectable = (item: IItem) => this._combatService.isSelectable(item);

    private split = (array, size) => {
        const result = [];

        if (!array) {
            return result;
        }

        for (let i = 0; i < array.length; i += size) {
            let chunk = array.slice(i, i + size);
            result.push(chunk);
        }

        return result;
    }
}
@let combat = game.combat;
@if (game.playState == 'Combat')
{
    <div id="combat" class="row">
        @if (enemiesPresent())
        {
            <div class="col-12">
                <h3 class="combat-header">{{ game.combat.roundHeader }}</h3>
                @for (enemyRow of  enemyRows; track enemyRow)
                {
                    <div class="row enemy-row">
                    @for (enemy of  enemyRow; track enemy)
                    {
                        <div [className]="'col-' + 12 / enemyRow.length" [ngClass]="{ 'unavailable': enemy.currentHitpoints <= 0 }">
                            <combat-participant [participant]="enemy"></combat-participant>
                        </div>
                    }
                    </div>
                }
                @for (characterRow of  characterRows; track characterRow)
                {
                    <div class="row character-row">
                        @for (turn of  characterRow; track turn.character)
                        {
                            <div [className]="'col-' + 12 / characterRow.length" [ngClass]="{ 'unavailable': turn.character.currentHitpoints <= 0 }">
                                <combat-participant [participant]="turn.character"></combat-participant>
                                @if (turn.item && turn.character.currentHitpoints > 0)
                                {
                                    <div>
                                        <div [ngClass]="{ 'not-applicable': !turn.item.targetType }">
                                            <span>{{ turn.item.targetType === 'Enemy' ? texts.attack : texts.aid }}</span>
                                            @if (filteredTargets(turn).length > 1)
                                            {
                                                <select class="custom-select" [(ngModel)]="turn.target">
                                                    @for (target of filteredTargets(turn); track target)
                                                    {
                                                        <option [ngValue]="target" >{{ target.name }}</option>
                                                    }
                                                </select>
                                            }
                                            @if (filteredTargets(turn).length === 1)
                                            {
                                                <input class="single-item" type="text" disabled="disabled" [ngModel]="turn.target.name" />
                                            }
                                        </div>
                                        @if (turn.itemsAvailable.length)
                                        {
                                            <div>
                                                <span>{{ turn.item.targetType === 'Enemy' ? texts.attackWith : turn.item.targetType ? texts.aidWith : texts.useCombatItem }}</span>
                                                @if (turn.itemsAvailable.length > 1)
                                                {
                                                    <select class="custom-select" (ngModelChange)="itemChange($event, turn)" [(ngModel)]="turn.item">
                                                        @for (item of turn.itemsAvailable; track item)
                                                        {
                                                            <option [ngValue]="item" disabled="{{ itemSelectable(item) ? '' : 'true' }}" [ngClass]="{'unselectable': !itemSelectable(item)}" >{{ getItemName(item) }}</option>
                                                        }
                                                    </select>
                                                }
                                                @if (turn.itemsAvailable.length === 1)
                                                {
                                                    <input class="single-item" type="text" disabled="disabled" [ngModel]="getItemName(turn.item)" />
                                                }
                                            </div>
                                        }
                                    </div>
                                }
                                @if (!turn.item && turn.character.currentHitpoints > 0)
                                {
                                    <div>
                                        <span>{{ game.combat.noActionText }}</span>
                                    </div>
                                }
                            </div>
                        }
                    </div>
                }
                <div class="row">
                    <div class="col-12 fight-row">
                        <button type="button" class="btn btn-danger" (click)="fight()" [disabled]="!actionsEnabled">{{ texts.fight }}</button>
                    </div>
                </div>
                <div class="row">
                    <ul class="list-unstyled combat-actions">
                        @for (action of  game.currentLocation.combatActions; track action)
                        {
                            <li>
                                <button type="button" class="btn" [ngClass]="getButtonClass(action)" (click)="executeAction(action)" [disabled]="!actionsEnabled">{{ action[1].text }}</button>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        }
        @if (!enemiesPresent())
        {
            <div id="combat-win">
                <h2 class="combat-win-header">{{ texts.combatWin }}</h2>
                <ul class="combat-winnings">
                    <li>
                        <span class="enemies-defeated-header">{{ texts.enemiesDefeated }}</span>
                        <ul>
                            @for (enemy of combat.winnings.enemiesDefeated; track enemy)
                            {
                                <li>{{ enemy.name }}</li>
                            }
                        </ul>
                    </li>
                    @if (combat.winnings.currency)
                    {
                        <li class="currency-won">{{ texts.format(texts.currencyWon, [combat.winnings.currency]) }}</li>
                    }
                    @if (combat.winnings.itemsWon.length)
                    {
                    <li>
                            <span class="items-taken-header">{{ texts.itemsTaken }}</span>
                            <ul>
                                @for (item of combat.winnings.itemsWon; track item)
                                {
                                    <li>{{ item.name }}</li>
                                }
                            </ul>
                    </li>
                    }
                </ul>
            </div>
        }
        <fieldset class="combatlog">
            <legend>{{ texts.messages }}</legend>
            <ul class="list-unstyled action-log">
                @for (message of  game.combatLog; track message)
                {
                    <li>{{ message }}</li>
                }
            </ul>
        </fieldset>
    </div>
}

// src/UserInterface/Components/Encounter/Combat.vue
<template>
  <dialog :open="playState === PlayState.Combat">
    <div id="combat" class="row">
      <div v-if="enemiesPresent(game)" class="col-12">
        <h3 class="combat-header">{{ game.combat.roundHeader }}</h3>

        <div v-for="enemyRow of enemyRows" class="row enemy-row">
          <div v-for="enemy of enemyRow" class="'col-' + 12 / enemyRow.length" :class="{ 'unavailable': enemy.currentHitpoints <= 0 }">
            <combat-participant :participant="enemy"></combat-participant>
          </div>
        </div>
        
        <div v-for="characterRow of characterRows" class="row character-row">
          <div v-for="turn of characterRow" class="'col-' + 12 / characterRow.length" :class="{ 'unavailable': turn.character.currentHitpoints <= 0 }">
            <combat-participant :participant="turn.character"></combat-participant>
            <div v-if="turn.item && turn.character.currentHitpoints > 0">
              <div :class="{ 'not-applicable': !turn.item.targetType }">
                <span>{{ turn.item.targetType === 'Enemy' ? texts.attack : texts.aid }}</span>
                <select v-if="filteredTargets(turn).length > 1" class="custom-select" v-model="turn.target">
                  <option v-for="target of filteredTargets(turn)" :value="target">{{ getTargetName(target) }}</option>
                </select>
                <input v-if="filteredTargets(turn).length === 1" class="single-item" type="text" :disabled="true" v-model="turn.target.name" />
              </div>
              <div v-if="turn.itemsAvailable.length">
                <span>{{ turn.item.targetType === 'Enemy' ? texts.attackWith : turn.item.targetType ? texts.aidWith : texts.useCombatItem }}</span>
                <select v-if="turn.itemsAvailable.length > 1" class="custom-select" @change="itemChange(turn.item, turn)" v-model="turn.item">
                  <option v-for="item of turn.itemsAvailable" :value="item" :disabled="!itemSelectable(item)" :class="{'unselectable': !itemSelectable(item)}" >{{ getItemName(item) }}</option>
                </select>
                <input v-if="turn.itemsAvailable.length === 1" class="single-item" type="text" :disabled="true" :value="getItemName(turn.item)" />
              </div>
            </div>
            <div v-if="!turn.item && turn.character.currentHitpoints > 0">
              <span>{{ game.combat.noActionText }}</span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-12 fight-row">
            <button type="button" class="btn btn-danger" @click="fight()" :disabled="!actionsEnabled">{{ texts.fight }}</button>
          </div>
        </div>
        <div class="row">
          <ul class="list-unstyled combat-actions">
            <li v-for="action of combatActions">
              <button type="button" class="btn" :class="getButtonClass(action)" @click="execute(action)" :disabled="!actionsEnabled">{{ action[1].text }}</button>
            </li>
          </ul>
        </div>
      </div>

      <div v-else id="combat-win">
        <h2 class="combat-win-header">{{ texts.combatWin }}</h2>
        <ul class="combat-winnings">
          <li>
            <span class="enemies-defeated-header">{{ texts.enemiesDefeated }}</span>
            <ul>
              <li v-for="enemy of combat.winnings.enemiesDefeated">{{ enemy.name }}</li>
            </ul>
          </li>
          <li v-if="combat.winnings.currency" class="currency-won">{{ texts.format(texts.currencyWon, [combat.winnings.currency.toString()]) }}</li>
          <li v-if="combat.winnings.itemsWon.length">
            <span class="items-taken-header">{{ texts.itemsTaken }}</span>
            <ul>
              <li v-for="item of combat.winnings.itemsWon">{{ item.name }}</li>
            </ul>
          </li>
        </ul>
      </div>

      <fieldset class="combatlog">
        <legend>{{ texts.messages }}</legend>
        <ul class="list-unstyled action-log">
          <li v-for="message of combatLog">{{ message }}</li>
        </ul>
      </fieldset>
    </div>
  </dialog>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {IEnemy} from "storyScript/Interfaces/enemy.ts";
import {IAction} from "storyScript/Interfaces/action.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {ICombatTurn} from "storyScript/Interfaces/combatTurn.ts";
import {ref} from "vue";
import {PlayState} from "storyScript/Interfaces/enumerations/playState.ts";
import {ICombatSetup} from "storyScript/Interfaces/combatSetup.ts";
import {enemiesPresent, executeAction, getButtonClass} from "vue/Helpers.ts";

const store = useStateStore();
const {game} = storeToRefs(store);
const {texts, dataService, itemService, combatService} = store.services;

const split = (array: any[], size: number): any[] => {
  const result = [];

  if (!array) {
    return result;
  }

  for (let i = 0; i < array.length; i += size) {
    let chunk = array.slice(i, i + size);
    result.push(chunk);
  }

  return result;
}

const {playState, combat} = defineProps<{
  playState: PlayState,
  combat: ICombatSetup<ICombatTurn>,
  combatActions: IAction[],
  combatLog: string[]
}>();

const actionsEnabled = ref(true);
const enemyRows = ref<Array<Array<IEnemy>> >(split(combat.enemies, 3));
const characterRows = ref<Array<Array<ICombatTurn>>>(split(combat, 3));

const getTargetName = (target: any) => target.name;

const getItemName = (item: IItem): string => itemService.getItemName(item);

const execute = (action: IAction) => executeAction(game.value, action, this, () => dataService.saveGame(game.value));

const itemChange = (item: IItem, turn: ICombatTurn) => {
  const currentTarget = turn.target;
  const targets = turn.targetsAvailable.concat(turn.character).filter(t => combatService.canTarget(item, t, turn.character));
  turn.target = targets.filter(t => t === currentTarget)[0] ?? targets[0];
}

const filteredTargets = (turn: ICombatTurn): IEnemy[] | ICombatTurn[] => turn.targetsAvailable.concat(turn.character).filter(t => combatService.canTarget(turn.item, t, turn.character));

const fight = (): void => {
  actionsEnabled.value = false;

  Promise.resolve(combatService.fight(combat)).then(() => {
    actionsEnabled.value = true;
    characterRows.value = split(combat, 3) as Array<Array<ICombatTurn>>;
  });
}

const itemSelectable = (item: IItem) => combatService.isSelectable(item);

</script>
