// src/UI/Angular/src/Components/Conversation/conversation.component.ts
import { IGame, Conversations } from '../../../../../Engine/Interfaces/storyScript';
import { ConversationService } from '../../../../../Engine/Services/ConversationService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './conversation.component.html';

@Component({
    selector: 'conversation',
    template: template,
})
export class ConversationComponent {
    constructor(private _conversationService: ConversationService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
    }

    game: IGame;

    answer = (node: Conversations.IConversationNode, reply: Conversations.IConversationReply): void => this._conversationService.answer(node, reply);

    getLines = (nodeOrReply: Conversations.IConversationNode | Conversations.IConversationReply): string => this._conversationService.getLines(nodeOrReply);
}
<div id="conversation" *ngIf="game.playState === 'Conversation'">
    <div id="conversation-options" *ngIf="game.person.conversation.activeNode">
        <div innerHTML="{{ getLines(game.person.conversation.activeNode) }}"></div>
        <div *ngFor="let reply of game.person.conversation.activeNode.replies.options">
            <div *ngIf="reply.available || reply.showWhenUnavailable">
                <input type="radio" [disabled]="!reply.available" (click)="answer(game.person.conversation.activeNode, reply)" /><span innerHTML="{{ getLines(reply) }}"></span>
            </div>
        </div>
    </div>
    <div *ngIf="!game.person.conversation.activeNode">
        Your conversation has ended.
    </div>
    <hr />
    <strong>Conversation history</strong>
    <ul class="list-unstyled" id="conversation-history">
        <li *ngFor="let entry of game.person.conversation.conversationLog">
            <div class="conversation-lines" innerHTML="{{ entry.lines }}"></div>
            <div class="conversation-option" innerHTML="{{ entry.reply }}"></div>
        </li>
    </ul>
</div>

// src/UserInterface/Components/Encounter/Conversation.vue
<template>
  <dialog :open="playState === PlayState.Conversation" class="dialog">
    <h1 v-if="person" class="dialog-title conversation-title">
      {{ (person.conversation.title || texts.format(texts.talk, [person.name])) }}
    </h1>
    <div class="dialog-body conversation-body">
      <div v-if="person?.conversation" id="conversation">

        <div v-if="person.conversation.activeNode" id="conversation-options">
          <div v-html="getLines(person.conversation.activeNode)"></div>
          <div v-for="reply of person.conversation.activeNode.replies">
          <div v-if="reply.available || reply.showWhenUnavailable" :class="{ 'unavailable': !reply.available }">
            <input type="radio" :disabled="!reply.available" @click="answer(person.conversation.activeNode, reply)" />
            <span v-html="getLines(reply)"></span>
          </div>
          </div>
        </div>
        
        <div v-if="!person.conversation.activeNode || !person.conversation.activeNode.replies.length">
          {{ texts.conversationEnded }}
        </div>

        <div id="conversation-history">
          <hr />
          <p id="conversation-history-title">Conversation history</p>
          <ul class="list-unstyled">
            <li v-for="entry of person.conversation.conversationLog">
              <div class="conversation-lines" v-html="entry.lines"></div>
              <div class="conversation-option" v-html="entry.reply"></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </dialog>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {PlayState} from "storyScript/Interfaces/enumerations/playState.ts";
import {IConversationNode} from "storyScript/Interfaces/conversations/conversationNode.ts";
import {IConversationReply} from "storyScript/Interfaces/conversations/conversationReply.ts";
import {IPerson} from "storyScript/Interfaces/person.ts";

const store = useStateStore();
const {texts, conversationService} = store.services;

const { playState, person } = defineProps<{
  person?: IPerson,
  playState?: PlayState
}>();

const answer = (node: IConversationNode, reply: IConversationReply): void => conversationService.answer(node, reply);

const getLines = (nodeOrReply: IConversationNode | IConversationReply): string => nodeOrReply?.lines || null;

</script>
