// src/UserInterface/Components/GameState/Intro.vue
<template>
  <div id="intro" class="box-container">
    <h2>Game introduction</h2>
    <p>Please copy the IntroComponent.html file to your game and add your introduction here.</p>
    <button class="btn btn-primary" type="button" @click="endIntro()">{{ texts.skipIntro }}</button>
  </div>
</template>
<script lang="ts" setup>

import {useStateStore} from "vue/StateStore.ts";

const store = useStateStore();
const {texts, gameService} = store.services;

const endIntro = (): void => gameService.restart(true);

</script>

// src/UI/Components/Intro/intro.component.ts
import { IGame, IInterfaceTexts } from 'storyScript/Interfaces/storyScript';
import { GameService } from 'storyScript/Services/gameService';
import { ObjectFactory } from 'storyScript/ObjectFactory';
import { Component, inject } from '@angular/core';
import { getTemplate } from '../../helpers';

@Component({
    selector: 'intro',
    template: getTemplate('intro', await import('./intro.component.html'))
})
export class IntroComponent {
    private _gameService: GameService;
  
    constructor() {
        this._gameService = inject(GameService);
        const objectFactory = inject(ObjectFactory);
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
    }

    game: IGame;
    texts: IInterfaceTexts;

    endIntro = (): void => this._gameService.restart(true);
}
@if (game.state === 'Intro')
{
    <div class="box-container" id="intro">
        <h2>Game introduction</h2>
        <p>Please copy the IntroComponent.html file to your game and add your introduction here.</p>
        <button type="button" class="btn btn-primary" (click)="endIntro()">{{ texts.skipIntro }}</button>
    </div>
}
