// src/UserInterface/Components/Equipment.vue
<template>
  <div v-if="showEquipment(character)" class="character-equipment box-container">
    <div class="box-title" @click="isCollapsed = !isCollapsed">{{ texts.equipmentHeader }}</div>
    <!-- TODO   [ngbCollapse]="isCollapsed"-->
    <div class="equipment-panel collapse navbar-collapse">
      <div v-if="isSlotUsed('head')" class="row">
        <div class="col-12">
          <div>
            {{ texts.head }}
          </div>
          <div class="item-box" @click="unequipItem(character.equipment.head)">
            {{ getItemName(character.equipment.head) }}
          </div>
        </div>
      </div>
      <div v-if="isSlotUsed('amulet')" class="row">
        <div class="col-12">
          <div>
            {{ texts.amulet }}
          </div>
          <div class="item-box" @click="unequipItem(character.equipment.amulet)">
            {{ getItemName(character.equipment.amulet) }}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <span v-if="isSlotUsed(['hands', 'rightHand', 'rightRing'])">{{ texts.rightHand }}</span>
        </div>
        <div class="col-6">
          <span v-if="isSlotUsed('body')">{{ texts.body }}</span>
        </div>
        <div class="col-3">
          <span v-if="isSlotUsed(['hands', 'leftHand', 'leftRing'])">{{ texts.leftHand }}</span>
        </div>
        <div class="col-3">
          <div v-if="isSlotUsed('hands')" class="item-box" @click="unequipItem(character.equipment.hands)">
            {{ getItemName(character.equipment.hands) }}
          </div>
          <div v-if="isSlotUsed('rightHand')" :class="{ 'side-borders' : isSlotUsed(['hands', 'rightRing']) }"
               class="item-box"
               @click="unequipItem(character.equipment.rightHand)">{{ getItemName(character.equipment.rightHand) }}
          </div>
          <div v-if="isSlotUsed('rightRing')" class="item-box" @click="unequipItem(character.equipment.rightRing)">
            {{ getItemName(character.equipment.rightRing) }}
          </div>
        </div>
        <div class="col-6">
          <div v-if="isSlotUsed(['rightHand', 'leftHand']) && isSlotUsed('hands')" class="item-box no-border"></div>
          <div v-if="isSlotUsed('body')" class="item-box" @click="unequipItem(character.equipment.body)">
            {{ getItemName(character.equipment.body) }}
          </div>
        </div>
        <div class="col-3">
          <div v-if="isSlotUsed('hands')" class="item-box" @click="unequipItem(character.equipment.hands)">
            {{ getItemName(character.equipment.hands) }}
          </div>
          <div v-if="isSlotUsed('leftHand')" :class="{ 'side-borders' : isSlotUsed(['hands', 'leftRing']) }"
               class="item-box"
               @click="unequipItem(character.equipment.leftHand)">{{ getItemName(character.equipment.leftHand) }}
          </div>
          <div v-if="isSlotUsed('leftRing')" class="item-box" @click="unequipItem(character.equipment.leftRing)">
            {{ getItemName(character.equipment.leftRing) }}
          </div>
        </div>
      </div>
      <div v-if="isSlotUsed('legs')" class="row">
        <div class="col-12">
          <div>
            {{ texts.legs }}
          </div>
          <div class="item-box" @click="unequipItem(character.equipment.legs)">
            {{ getItemName(character.equipment.legs) }}
          </div>
        </div>
      </div>
      <div v-if="isSlotUsed('feet')" class="row">
        <div class="col-12">
          <div>
            {{ texts.feet }}
          </div>
          <div class="item-box" @click="unequipItem(character.equipment.feet)">
            {{ getItemName(character.equipment.feet) }}
          </div>
        </div>
      </div>
      <div v-for="slot of customSlots()" class="row">
        <div v-if="isSlotUsed(slot)" class="col-12">
          <div>
            {{ texts[slot] }}
          </div>
          <div class="item-box" @click="unequipItem(character.equipment[slot])">
            {{ getItemName(character.equipment[slot]) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import {useStateStore} from "vue/StateStore.ts";
import {storeToRefs} from "pinia";
import {DefaultEquipment} from "storyScript/Interfaces/defaultEquipment.ts";
import {IItem} from "storyScript/Interfaces/item.ts";
import {ICharacter} from "storyScript/Interfaces/character.ts";
import {showEquipment} from "vue/Helpers.ts";
import {ref} from "vue";

const store = useStateStore();
const {game, texts} = storeToRefs(store);

const {character} = defineProps<{
  character?: ICharacter
}>();

const isCollapsed = ref(false);
const itemService = store.getItemService();
const characterService = store.getCharacterService();

const customSlots = (): string[] => {
  const defaultSlots = Object.keys(new DefaultEquipment());
  return Object.keys(character.equipment).filter(e => defaultSlots.indexOf(e) === -1)
};

const getItemName = (item: IItem): string => itemService.getItemName(item);

const unequipItem = (item: IItem): boolean => itemService.unequipItem(character, item);

const isSlotUsed = (slot: string | string[]): boolean => {
  const slots = Array.isArray(slot) ? slot : [slot];
  return slots.find(s => characterService.isSlotUsed(character, s)) !== undefined;
}

</script>

// src/UI/Angular/src/Components/Equipment/equipment.component.ts
import { IGame, IInterfaceTexts, IItem } from '../../../../../Engine/Interfaces/storyScript';
import { SharedMethodService } from '../../Services/SharedMethodService';
import { CharacterService } from '../../../../../Engine/Services/characterService';
import { ObjectFactory } from '../../../../../Engine/ObjectFactory';
import { Component } from '@angular/core';
import template from './equipment.component.html';

@Component({
    selector: 'equipment',
    template: template,
})
export class EquipmentComponent {
    constructor(private _sharedMethodService: SharedMethodService, private _characterService: CharacterService, objectFactory: ObjectFactory) {
        this.game = objectFactory.GetGame();
        this.texts = objectFactory.GetTexts();
        this._sharedMethodService.useEquipment = true;
    }

    game: IGame;
    texts: IInterfaceTexts;

    showEquipment = (): boolean => this._sharedMethodService.showEquipment(this.game);

    unequipItem = (item: IItem): boolean => this._characterService.unequipItem(item);

    isSlotUsed = (slot: string): boolean => {
        return this._characterService.isSlotUsed(slot);
    }
}
<div class="box-container" id="character-equipment" *ngIf="showEquipment()">
    <div class="box-title" (click)="isCollapsed = !isCollapsed">{{ texts.equipmentHeader }}</div>
    <div id="equipment-panel" [ngbCollapse]="isCollapsed" class="collapse navbar-collapse">
        <div class="row" *ngIf="isSlotUsed('head')">
            <div class="col-12">
                <div>
                    {{ texts.head }}
                </div>
                <div class="item-box" (click)="unequipItem(game.character.equipment.head)">
                    {{ game.character.equipment.head?.name }}
                </div>
            </div>
        </div>
        <div class="row" *ngIf="isSlotUsed('amulet')">
            <div class="col-12">
                <div>
                    {{ texts.amulet }}
                </div>
                <div class="item-box" (click)="unequipItem(game.character.equipment.amulet)">
                    {{ game.character.equipment.amulet?.name }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <span *ngIf="isSlotUsed('hands') || isSlotUsed('rightHand') || isSlotUsed('rightRing')">{{ texts.rightHand }}</span>
            </div>
            <div class="col-6">
                <span *ngIf="isSlotUsed('body')">{{ texts.body }}</span>
            </div>
            <div class="col-3">
                <span *ngIf="isSlotUsed('hands') || isSlotUsed('leftHand') || isSlotUsed('leftRing')">{{ texts.leftHand }}</span>
            </div>
            <div class="col-3">
                <div class="item-box" *ngIf="isSlotUsed('hands')" (click)="unequipItem(game.character.equipment.hands)">{{ game.character.equipment.hands?.name }}</div>
                <div class="item-box" [ngClass]="{ 'side-borders' : isSlotUsed('hands') || isSlotUsed('rightRing') }" *ngIf="isSlotUsed('rightHand')" (click)="unequipItem(game.character.equipment.rightHand)">{{ game.character.equipment.rightHand?.name }}</div>
                <div class="item-box" *ngIf="isSlotUsed('rightRing')" (click)="unequipItem(game.character.equipment.rightRing)">{{ game.character.equipment.rightRing?.name }}</div>
            </div>
            <div class="col-6">
                <div class="item-box no-border" *ngIf="(isSlotUsed('rightHand') || isSlotUsed('leftHand')) && isSlotUsed('hands')"></div>
                <div class="item-box" *ngIf="isSlotUsed('body')" (click)="unequipItem(game.character.equipment.body)">{{ game.character.equipment.body?.name }}</div>
            </div>
            <div class="col-3">
                <div class="item-box" *ngIf="isSlotUsed('hands')" (click)="unequipItem(game.character.equipment.hands)">{{ game.character.equipment.hands?.name }}</div>
                <div class="item-box" [ngClass]="{ 'side-borders' : isSlotUsed('hands') || isSlotUsed('leftRing') }" *ngIf="isSlotUsed('leftHand')" (click)="unequipItem(game.character.equipment.leftHand)">{{ game.character.equipment.leftHand?.name }}</div>
                <div class="item-box" *ngIf="isSlotUsed('leftRing')" (click)="unequipItem(game.character.equipment.leftRing)">{{ game.character.equipment.leftRing?.name }}</div>
            </div>
        </div>
        <div class="row" *ngIf="isSlotUsed('legs')">
            <div class="col-12">
                <div>
                    {{ texts.legs }}
                </div>
                <div class="item-box" (click)="unequipItem(game.character.equipment.legs)">
                    {{ game.character.equipment.legs?.name }}
                </div>
            </div>
        </div>
        <div class="row" *ngIf="isSlotUsed('feet')">
            <div class="col-12">
                <div>
                    {{ texts.feet }}
                </div>
                <div class="item-box" (click)="unequipItem(game.character.equipment.feet)">
                    {{ game.character.equipment.feet?.name }}
                </div>
            </div>
        </div>
    </div>
</div>
